export const chonqua = {
  products: [
    {
      productInfo: {
        sku: "230803500",
        skuId: "230803500",
        name: "Máy sấy tóc Dreame Hair Glory AHD6A-RS (Rose Gold)",
        imageUrl:
          "https://lh3.googleusercontent.com/VlOzSHLWV2iCGXYgLr3Mgi9JR_rV20NFUqZQzM0AYd7VSXXmnAkst1tnlE5jKxrN9n-KNyMlE_0bF205dxn8o3ZJjnXiCFJTvg",
        tags: [],
        brand: {
          code: "dreame",
          name: "Dreame",
          logo: "",
          id: 12008,
        },
        categories: [
          {
            code: "NH12",
            name: "Điện máy",
            id: 386106,
            isAdult: false,
          },
          {
            code: "NH12-03",
            name: "Điện gia dụng",
            id: 386702,
            isAdult: false,
          },
          {
            code: "NH12-03-99",
            name: "Điện gia dụng khác",
            id: 386732,
            isAdult: false,
          },
          {
            code: "NH12-03-99-01",
            name: "Dụng cụ làm đẹp",
            id: 386733,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "may-say-toc-dreame-hair-glory-ahd6a-rs-rose",
        sellerSku: "230803500",
        canonical: "may-say-toc-dreame-hair-glory-ahd6a-rs-rose--s230803500",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "6973734684256",
        shippingType: "NORMAL",
        displayName: "Máy sấy tóc Dreame Hair Glory AHD6A-RS (Rose Gold)",
        imageLabel: "",
      },
      promotions: [
        {
          id: 500129,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 2500000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: [
              {
                imageUrl:
                  "https://shopfront-cdn.tekoapis.com/cart/gift-filled.png",
                name: "Giảm 3.200.000₫ (áp dụng vào giá sản phẩm)",
                selectName:
                  "Giảm 1.000.000₫ (áp dụng vào giá sản phẩm ) 1x Balo laptop Targus 15.6 TSB883 Black (Safire) (Quà tặng - logo Phong Vũ)",
                content:
                  "Khuyến mãi áp dụng khi mua đủ 1 sản phẩm, mua tối thiểu 1 sản phẩm",
                endDate: "31/12/2023",
              },
              {
                imageUrl:
                  "https://shopfront-cdn.tekoapis.com/cart/gift-filled.png",
                name: "1x Mã giảm thêm 150.000 cho một số chuột Logitech, MSI, Newmen, Asus, Tai nghe Zidli",
                selectName:
                  "Giảm 1.000.000₫ (áp dụng vào giá sản phẩm ) 1x Balo laptop Targus 15.6 TSB883 Black (Safire) (Quà tặng - logo Phong Vũ)",
                content:
                  "Khuyến mãi áp dụng khi mua đủ 1 sản phẩm, mua tối thiểu 1 sản phẩm",
                endDate: "31/12/2023",
              },
            ],
            bulkDiscount: null,
          },
          applyOn: "product",
          description: "Oct 2023 | Flash Sales Online - SDA",
          endTimestampSec: "1698166799",
          name: "Oct 2023 | Flash Sales Online - SDA 115",
          type: "product",
          landing: null,
        },
      ],
      images: [
        {
          url: "https://lh3.googleusercontent.com/BmomL_U0wjMpue8fZ3M13tI-zfyzFEbsjgr4ew9we-L2_lvH5xjPv6BSWbobCWG1WEBQUUJVClZr-eUxU7AufxFq6Vkwm6O5",
          priority: 1,
          label: "",
        },
        {
          url: "https://lh3.googleusercontent.com/Cgt-dMuQOYlpXw6JwGUf0-gkErJBGqcPVLsg0VmAxefdlp7bBmxqlxLyqOok2TTGUDz1yWfD--sMUs1VeJrcIbDIif0OcioN",
          priority: 2,
          label: "",
        },
        {
          url: "https://lh3.googleusercontent.com/A2CAnMbhuHMNTFBV-idB5TT-ppCi3i0mALNB_vGCkRlIWQ3Xcy9MmD9CU5_DOTzGfwm1dTS8431efB_Aw7Onr0C4jjMNibxf_w",
          priority: 3,
          label: "",
        },
        {
          url: "https://lh3.googleusercontent.com/OPYA2E7eZ6gVzX3sX1qEkwDzK0tXuJl-WFIlSL9rz_WMpuu_DQQu06NCAOZ9m7vmEIjfxXuZQRfttW1-NJwpETWa_xt3ENsHNQ",
          priority: 4,
          label: "",
        },
        {
          url: "https://lh3.googleusercontent.com/awXbDOrta3HE6ha4CkIsFBY7cYmm9_2DYER7T33nnV9e0LlexfCJl1qM9yosNoi5a8n0x1T6xP4q4aTMXgP8_YEV7fTPxChXhQ",
          priority: 5,
          label: "",
        },
        {
          url: "https://lh3.googleusercontent.com/PsUuI2hwkVW80oomorNr55Q8oZROdeeunKN5qgWM7Z8yxeOTrfS3HH4rwDK3nOdaH0aRchG4AMz1EjHcW9YvqK1Irspu-9bo",
          priority: 6,
          label: "",
        },
        {
          url: "https://lh3.googleusercontent.com/6yGbTy8Nm6cQehNU7plm9GD3shAGR2pJdCG-4CxzJwmD5ZAaAGvyg6YFNjz2Ovn1u-kDmOBcyhBMXReNNPr0_uYkdw9WMzw",
          priority: 7,
          label: "",
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "4990000",
          terminalPrice: "4990000",
          latestPrice: "2490000",
          discountAmount: "2500000",
          discountPercent: 50.1,
          sellPrice: "4990000",
          minLatestPrice: "2490000",
          maxLatestPrice: "2490000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "\u003cul\u003e\u003cli\u003eThiết kế gọn nhẹ\u003c/li\u003e\u003cli\u003e4 chế độ nhiệt\u003c/li\u003e\u003cli\u003e2 chế độ gió\u003c/li\u003e\u003cli\u003eSấy khô hiệu quả và nhanh chóng\u003c/li\u003e\u003cli\u003eCông nghệ ion bảo vệ da đầu khỏe mạnh\u003c/li\u003e\u003c/ul\u003e",
    },
    {
      productInfo: {
        sku: "221100983",
        skuId: "221100983",
        name: "Máy Uốn Tóc Tự Xoay Ion Âm Halio Auto Rotating Hair Curler",
        imageUrl:
          "https://lh3.googleusercontent.com/t7cGymgFqIHJlOweixULACQ8pDWnQ6agUn4OSMvD-HrzAvp22-QE2KHbZUDMOgNjtgWj_YlLe3yS-WBYEW9DntdVhkC7z_8U",
        tags: [],
        brand: {
          code: "halio",
          name: "Halio",
          logo: "",
          id: 12029,
        },
        categories: [
          {
            code: "NH12",
            name: "Điện máy",
            id: 386106,
            isAdult: false,
          },
          {
            code: "NH12-03",
            name: "Điện gia dụng",
            id: 386702,
            isAdult: false,
          },
          {
            code: "NH12-03-99",
            name: "Điện gia dụng khác",
            id: 386732,
            isAdult: false,
          },
          {
            code: "NH12-03-99-01",
            name: "Dụng cụ làm đẹp",
            id: 386733,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "may-uon-toc-tu-xoay-ion-am-halio-auto-rotating-hair-curler",
        sellerSku: "221100983",
        canonical:
          "may-uon-toc-tu-xoay-ion-am-halio-auto-rotating-hair-curler--s221100983",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "810052060637",
        shippingType: "NORMAL",
        displayName:
          "Máy Uốn Tóc Tự Xoay Ion Âm Halio Auto Rotating Hair Curler",
        imageLabel:
          "Máy Uốn Tóc Tự Xoay Ion Âm Halio Auto Rotating Hair Curler",
      },
      promotions: [
        {
          id: 500130,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: null,
            gifts: [
              {
                sku: "221101562",
                name: "Bao da nắp gập Tab A7 Lite, Xám (EF-BT220PJEGWW) (Quà tặng)",
                imageUrl:
                  "https://lh3.googleusercontent.com/ZbZHVZ_Rz59_cbMjfHCM2Ere9yqov5BGBhe-46ASR7a0JW1jbayOoQexISRQSnPqtSUP3j61OdSLy96AKDFziP7ipLuChu9Y",
                quantity: 1,
                maxQuantityPerOrder: null,
                quantityDecimal: 1,
                maxQuantityPerOrderDecimal: null,
              },
            ],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description: "Oct 2023 | Flash Sales Online - SDA",
          endTimestampSec: "1698166799",
          name: "Oct 2023 | Flash Sales Online - SDA 116",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "990000",
          terminalPrice: "990000",
          latestPrice: "749000",
          discountAmount: "241000",
          discountPercent: 24.34,
          sellPrice: "990000",
          minLatestPrice: "749000",
          maxLatestPrice: "749000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "\u003cp\u003e- Trục gốm phủ Tourmaline Giúp tóc bóng mượt\u003cbr\u003e- Trục tự xoay 360 độ Tạo kiểu dễ dàng trong 15 phút\u003cbr\u003e- Đầu cách nhiệt Đảm bảo an toàn cho người sử dụng\u003cbr\u003e- 4 chế độ nhiệt 140°C-160°C-180°-200°C Phù hợp cho mọi loại tóc\u003c/p\u003e",
    },
    {
      productInfo: {
        sku: "220801566",
        skuId: "220801566",
        name: "Máy triệt lông lạnh cá nhân Halio IPL Cooling Hair Removal Device",
        imageUrl:
          "https://lh3.googleusercontent.com/pOj-qIpNot1wY3kfKfzX_wjrGImtHDG31ZFBZ0GZnsILHxMrMyydS4oxD1-B8bqs3xcGmOSg4rQNDxWGHvtFFWPtI1ytXGM",
        tags: [],
        brand: {
          code: "halio",
          name: "Halio",
          logo: "",
          id: 0,
        },
        categories: [
          {
            code: "NH12",
            name: "Điện máy",
            id: 386106,
            isAdult: false,
          },
          {
            code: "NH12-03",
            name: "Điện gia dụng",
            id: 386702,
            isAdult: false,
          },
          {
            code: "NH12-03-99",
            name: "Điện gia dụng khác",
            id: 386732,
            isAdult: false,
          },
          {
            code: "NH12-03-99-01",
            name: "Dụng cụ làm đẹp",
            id: 386733,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [
          {
            code: "004",
            name: "Chăm sóc sức khoẻ",
            id: 586,
            isAdult: false,
          },
          {
            code: "004-001",
            name: "Chăm sóc cá nhân",
            id: 587,
            isAdult: false,
          },
          {
            code: "004-001-008",
            name: "Sản phẩm chăm sóc cá nhân khác",
            id: 614,
            isAdult: false,
          },
        ],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "may-triet-long-lanh-ca-nhan-halio-ipl-cooling-hair-removal-device",
        sellerSku: "220801566",
        canonical:
          "may-triet-long-lanh-ca-nhan-halio-ipl-cooling-hair-removal-device--s220801566",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "810052060668",
        shippingType: "NORMAL",
        displayName:
          "Máy triệt lông lạnh cá nhân Halio IPL Cooling Hair Removal Device",
        imageLabel: "",
      },
      promotions: [
        {
          id: 500131,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 951000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description: "Oct 2023 | Flash Sales Online - SDA",
          endTimestampSec: "1698166799",
          name: "Oct 2023 | Flash Sales Online - SDA 117",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "4000000",
          terminalPrice: "4000000",
          latestPrice: "3049000",
          discountAmount: "951000",
          discountPercent: 23.78,
          sellPrice: "4000000",
          minLatestPrice: "3049000",
          maxLatestPrice: "3049000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "\u003cp\u003e- Triệt lông vĩnh viễn tại nhà với công nghệ IPL tiên tiến hiệu quả nhanh, lâu dài\u003cbr\u003e- Màn hình LCD hiển thị rõ ràng số xung còn lại, chế độ xung và cường độ ánh sáng\u003cbr\u003e- Thiết kế nhỏ gọn, dễ dàng cầm nắm và di chuyển khi sử dụng trên bề mặt da\u003cbr\u003e- Tuổi thọ máy cao với 999,999 lần xung - đem lại cho bạn trải nghiệm triệt lông không giới hạn\u003cbr\u003e- Khôi phục đàn hồi cho da và trẻ hóa làn da căng tràn sức sống\u003c/p\u003e",
    },
    {
      productInfo: {
        sku: "220801562",
        skuId: "220801562",
        name: "Máy rửa mặt Halio Sensitive Facial Cleansing \u0026 Massaging Device Baby Pink",
        imageUrl:
          "https://lh3.googleusercontent.com/lMpmTWM_EiCoR7-ukJgyPhR6hTPnDj4oMYQqMRAg2-fkCAg_F0PO4QUKIUvj4y2dGtuvv1FYFJRP7OnkIvb4vDJl6JNQrAeS",
        tags: [],
        brand: {
          code: "halio",
          name: "Halio",
          logo: "",
          id: 0,
        },
        categories: [
          {
            code: "NH12",
            name: "Điện máy",
            id: 386106,
            isAdult: false,
          },
          {
            code: "NH12-03",
            name: "Điện gia dụng",
            id: 386702,
            isAdult: false,
          },
          {
            code: "NH12-03-99",
            name: "Điện gia dụng khác",
            id: 386732,
            isAdult: false,
          },
          {
            code: "NH12-03-99-01",
            name: "Dụng cụ làm đẹp",
            id: 386733,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [
          {
            code: "004",
            name: "Chăm sóc sức khoẻ",
            id: 586,
            isAdult: false,
          },
          {
            code: "004-001",
            name: "Chăm sóc cá nhân",
            id: 587,
            isAdult: false,
          },
          {
            code: "004-001-008",
            name: "Sản phẩm chăm sóc cá nhân khác",
            id: 614,
            isAdult: false,
          },
        ],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "may-rua-mat-halio-sensitive-facial-cleansing-\u0026-massaging-device-baby-pink",
        sellerSku: "220801562",
        canonical:
          "may-rua-mat-halio-sensitive-facial-cleansing-\u0026-massaging-device-baby-pink--s220801562",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "858681007883",
        shippingType: "NORMAL",
        displayName:
          "Máy rửa mặt Halio Sensitive Facial Cleansing \u0026 Massaging Device Baby Pink",
        imageLabel: "",
      },
      promotions: [
        {
          id: 500132,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 210000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description: "Oct 2023 | Flash Sales Online - SDA",
          endTimestampSec: "1698166799",
          name: "Oct 2023 | Flash Sales Online - SDA 118",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: 5,
      prices: [
        {
          supplierRetailPrice: "829000",
          terminalPrice: "829000",
          latestPrice: "619000",
          discountAmount: "210000",
          discountPercent: 25.33,
          sellPrice: "829000",
          minLatestPrice: "619000",
          maxLatestPrice: "619000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "\u003cp\u003e- Đầu gai silicon cao cấp, kháng khuẩn, siêu mảnh chỉ 0.6mm\u0026nbsp;\u003cbr\u003e- Làm sạch sâu và loại bỏ tới 99.5% bụi bẩn và dầu thừa\u003cbr\u003e- Chu trình tiêu chuẩn làm sạch tự động ngắt sau 2 phút\u003cbr\u003e- Với thiết kế đặc biệt chỉ sở hữu 3 chế độ rung phù hợp với làn da nhạy cảm và hạn chế người dùng chọn những mức độ quá lớn làm tổn thương da.\u003c/p\u003e",
    },
    {
      productInfo: {
        sku: "220303291",
        skuId: "220303291",
        name: "Máy làm sữa hạt sinh tố Tefal BL83SD66 1400W",
        imageUrl:
          "https://lh3.googleusercontent.com/Zr8LyivIU9xe7dFIenty6h-lPfyBDJS_1FWpCAnOULh-IkBg4CkipR71i2R7_G61S4eymftAnd1XXY13RAW1olSlL0CEYtiM",
        tags: [],
        brand: {
          code: "tefal",
          name: "TEFAL",
          logo: "",
          id: 11913,
        },
        categories: [
          {
            code: "NH12",
            name: "Điện máy",
            id: 386106,
            isAdult: false,
          },
          {
            code: "NH12-03",
            name: "Điện gia dụng",
            id: 386702,
            isAdult: false,
          },
          {
            code: "NH12-03-02",
            name: "Điện gia dụng nấu nướng và chế biến",
            id: 386713,
            isAdult: false,
          },
          {
            code: "NH12-03-02-06",
            name: "Máy xay, ép trái cây",
            id: 386719,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [
          {
            code: "008",
            name: "Đồ gia dụng",
            id: 1691,
            isAdult: false,
          },
          {
            code: "008-001",
            name: "Đồ dùng nhà bếp",
            id: 1692,
            isAdult: false,
          },
          {
            code: "008-001-007",
            name: "Máy xay ép",
            id: 1737,
            isAdult: false,
          },
          {
            code: "008-001-007-004",
            name: "Máy xay ép đa năng",
            id: 1743,
            isAdult: false,
          },
        ],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "may-lam-sua-hat-sinh-to-tefal-bl83sd66-1400w",
        sellerSku: "220303291",
        canonical: "may-lam-sua-hat-sinh-to-tefal-bl83sd66-1400w--s220303291",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "3016667246405",
        shippingType: "NORMAL",
        displayName: "Máy làm sữa hạt sinh tố Tefal BL83SD66 1400W",
        imageLabel: "Máy làm sữa hạt sinh tố Tefal BL83SD66 1400W",
      },
      promotions: [
        {
          id: 500134,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: null,
            gifts: [
              {
                sku: "221101562",
                name: "Bao da nắp gập Tab A7 Lite, Xám (EF-BT220PJEGWW) (Quà tặng)",
                imageUrl:
                  "https://lh3.googleusercontent.com/ZbZHVZ_Rz59_cbMjfHCM2Ere9yqov5BGBhe-46ASR7a0JW1jbayOoQexISRQSnPqtSUP3j61OdSLy96AKDFziP7ipLuChu9Y",
                quantity: 1,
                maxQuantityPerOrder: null,
                quantityDecimal: 1,
                maxQuantityPerOrderDecimal: null,
              },
            ],
            voucher: [
              {
                imageUrl:
                  "https://shopfront-cdn.tekoapis.com/cart/gift-filled.png",
                name: "Giảm 3.200.000₫ (áp dụng vào giá sản phẩm)",
                selectName:
                  "Giảm 1.000.000₫ (áp dụng vào giá sản phẩm ) 1x Balo laptop Targus 15.6 TSB883 Black (Safire) (Quà tặng - logo Phong Vũ)",
                content:
                  "Khuyến mãi áp dụng khi mua đủ 1 sản phẩm, mua tối thiểu 1 sản phẩm",

                endDate: "31/12/2023",
              },
              {
                imageUrl:
                  "https://shopfront-cdn.tekoapis.com/cart/gift-filled.png",
                name: "1x Mã giảm thêm 600.000đ cho màn hình LG Gram View",
                selectName:
                  "Giảm 1.000.000₫ (áp dụng vào giá sản phẩm ) 1x Balo laptop Targus 15.6 TSB883 Black (Safire) (Quà tặng - logo Phong Vũ)",
                content:
                  "Khuyến mãi áp dụng khi mua đủ 1 sản phẩm, mua tối thiểu 1 sản phẩm",
                endDate: "31/12/2023",
              },
            ],
            bulkDiscount: null,
          },
          applyOn: "product",
          description: "Oct 2023 | Flash Sales Online - SDA",
          endTimestampSec: "1698166799",
          name: "Oct 2023 | Flash Sales Online - SDA 120",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "6490000",
          terminalPrice: "6490000",
          latestPrice: "2949000",
          discountAmount: "3541000",
          discountPercent: 54.56,
          sellPrice: "6490000",
          minLatestPrice: "2949000",
          maxLatestPrice: "2949000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "\u003cp\u003e- Công suất: 1400 W\u003cbr\u003e- Gồm 1 cối lớn thủy tinh dung tích 1.75L, và 1 xửng hấp bằng nhựa\u003cbr\u003e- Lưỡi dao Powelix 6 cánh sắc bén\u003cbr\u003e- Chức năng: xay nấu thực phẩm, giúp giữ trọn dưỡng chất, loại bỏ không khí bên ngoài giúp thực phẩm không bị oxy hóa.\u003cbr\u003e- 10 chức năng được cài đặt sẵn (5 công thức nấu nóng và 5 công thức làm lạnh)\u003cbr\u003e- Màn hình kỹ thuật sỗ thông minh, dễ dàng thao tác\u003c/p\u003e",
    },
    {
      productInfo: {
        sku: "230803499",
        skuId: "230803499",
        name: "Máy sấy tóc Dreame Hair Glory AHD6A-WH (Trắng)",
        imageUrl:
          "https://lh3.googleusercontent.com/89SKHNOpczy4-JXUhtQaghXQPABU2eG5HNySxXWU6ZNKKxyesgYkZV8FCxywNP750ozMKzjN9Bx93LYcQ9utHGf47sRrZsf4",
        tags: [],
        brand: {
          code: "dreame",
          name: "Dreame",
          logo: "",
          id: 12008,
        },
        categories: [
          {
            code: "NH12",
            name: "Điện máy",
            id: 386106,
            isAdult: false,
          },
          {
            code: "NH12-03",
            name: "Điện gia dụng",
            id: 386702,
            isAdult: false,
          },
          {
            code: "NH12-03-99",
            name: "Điện gia dụng khác",
            id: 386732,
            isAdult: false,
          },
          {
            code: "NH12-03-99-01",
            name: "Dụng cụ làm đẹp",
            id: 386733,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "may-say-toc-dreame-hair-glory-ahd6a-wh-trang",
        sellerSku: "230803499",
        canonical: "may-say-toc-dreame-hair-glory-ahd6a-wh-trang--s230803499",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "6973734684270",
        shippingType: "NORMAL",
        displayName: "Máy sấy tóc Dreame Hair Glory AHD6A-WH (Trắng)",
        imageLabel: "",
      },
      promotions: [
        {
          id: 500128,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 2500000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description: "Oct 2023 | Flash Sales Online - SDA",
          endTimestampSec: "1698166799",
          name: "Oct 2023 | Flash Sales Online - SDA 114",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "4990000",
          terminalPrice: "4990000",
          latestPrice: "2490000",
          discountAmount: "2500000",
          discountPercent: 50.1,
          sellPrice: "4990000",
          minLatestPrice: "2490000",
          maxLatestPrice: "2490000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "\u003cul\u003e\u003cli\u003eThiết kế gọn nhẹ\u003c/li\u003e\u003cli\u003e4 chế độ nhiệt\u003c/li\u003e\u003cli\u003e2 chế độ gió\u003c/li\u003e\u003cli\u003eSấy khô hiệu quả và nhanh chóng\u003c/li\u003e\u003cli\u003eCông nghệ ion bảo vệ da đầu khỏe mạnh\u003c/li\u003e\u003c/ul\u003e",
    },
    {
      productInfo: {
        sku: "220920165",
        skuId: "220920165",
        name: "Máy xay sinh tố mini Bear LLJ-B03C1",
        imageUrl:
          "https://lh3.googleusercontent.com/4PKWke9UO2HlWSFj_93cVsyC7C6ZJHX_0db49VFKmm6jB7MyHESE2OGFQ3g7ftfQddg7HY8jZFaI51Q6rNsTLMFV6At3GlQ",
        tags: [],
        brand: {
          code: "bear",
          name: "BEAR",
          logo: "",
          id: 0,
        },
        categories: [
          {
            code: "NH12",
            name: "Điện máy",
            id: 386106,
            isAdult: false,
          },
          {
            code: "NH12-03",
            name: "Điện gia dụng",
            id: 386702,
            isAdult: false,
          },
          {
            code: "NH12-03-02",
            name: "Điện gia dụng nấu nướng và chế biến",
            id: 386713,
            isAdult: false,
          },
          {
            code: "NH12-03-02-06",
            name: "Máy xay, ép trái cây",
            id: 386719,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 18,
          description: "",
        },
        slug: "may-xay-sinh-to-mini-bear-llj-b03c1",
        sellerSku: "220920165",
        canonical: "may-xay-sinh-to-mini-bear-llj-b03c1--s220920165",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "6940971227188",
        shippingType: "NORMAL",
        displayName: "Máy xay sinh tố mini Bear LLJ-B03C1",
        imageLabel: "",
      },
      promotions: [
        {
          id: 500133,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 60000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description: "Oct 2023 | Flash Sales Online - SDA",
          endTimestampSec: "1698166799",
          name: "Oct 2023 | Flash Sales Online - SDA 119",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "799000",
          terminalPrice: "650000",
          latestPrice: "590000",
          discountAmount: "209000",
          discountPercent: 26.16,
          sellPrice: "650000",
          minLatestPrice: "590000",
          maxLatestPrice: "590000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "\u003cp\u003e- Máy xay sinh tố có thiết kế kiểu cầm tay nhỏ gọn, sử dụng pin sạc tiện lợi dùng bất cứ khi nào.\u003cbr\u003e- Công suất 50W xay được các loại thực phẩm mềm như chuối, bơ, dâu, đá viên nhỏ... \u0026nbsp;\u003cbr\u003e- Cốc xay 0.3 lít có quai xách tiện lợi mang theo du lịch, thể thao, dã ngoại hay đi làm đều được.\u003cbr\u003e- Lưỡi dao inox 304 không gỉ, sắc bén, an toàn vệ sinh thực phẩm.\u003cbr\u003e- Cốc bằng nhựa ABS cứng cáp, an toàn, dễ chùi rửa.\u003c/p\u003e",
    },
    {
      productInfo: {
        sku: "220400808",
        skuId: "220400808",
        name: "Máy xay sinh tố Deerma NU90",
        imageUrl:
          "https://lh3.googleusercontent.com/p-XhofJyuvIZgNpYomluwtEDc30KUtFf9mG_HLL-FybQVzurJfwHtF-OEF0MJNXCn2juRDE5HoDriNtOtpo1rcw1YfA5iACrBw",
        tags: ["Deerma-May22"],
        brand: {
          code: "deerma",
          name: "Deerma",
          logo: "",
          id: 11910,
        },
        categories: [
          {
            code: "NH12",
            name: "Điện máy",
            id: 386106,
            isAdult: false,
          },
          {
            code: "NH12-03",
            name: "Điện gia dụng",
            id: 386702,
            isAdult: false,
          },
          {
            code: "NH12-03-02",
            name: "Điện gia dụng nấu nướng và chế biến",
            id: 386713,
            isAdult: false,
          },
          {
            code: "NH12-03-02-06",
            name: "Máy xay, ép trái cây",
            id: 386719,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [
          {
            code: "008",
            name: "Đồ gia dụng",
            id: 1691,
            isAdult: false,
          },
          {
            code: "008-001",
            name: "Đồ dùng nhà bếp",
            id: 1692,
            isAdult: false,
          },
          {
            code: "008-001-007",
            name: "Máy xay ép",
            id: 1737,
            isAdult: false,
          },
          {
            code: "008-001-007-001",
            name: "Máy xay sinh tố",
            id: 1738,
            isAdult: false,
          },
          {
            code: "008-001-007-001-001",
            name: "Máy xay sinh tố gia đình",
            id: 1739,
            isAdult: false,
          },
        ],
        tax: {
          taxOut: 8,
          taxOutCode: "8",
        },
        warranty: {
          months: 6,
          description: "",
        },
        slug: "may-xay-sinh-to-deerma-nu90",
        sellerSku: "220400808",
        canonical: "may-xay-sinh-to-deerma-nu90--s220400808",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "6955578041518",
        shippingType: "NORMAL",
        displayName: "Máy xay sinh tố Deerma NU90",
        imageLabel: "",
      },
      promotions: [
        {
          id: 500135,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 51000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description: "Oct 2023 | Flash Sales Online - SDA",
          endTimestampSec: "1698166799",
          name: "Oct 2023 | Flash Sales Online - SDA 121",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "649000",
          terminalPrice: "550000",
          latestPrice: "499000",
          discountAmount: "150000",
          discountPercent: 23.11,
          sellPrice: "550000",
          minLatestPrice: "499000",
          maxLatestPrice: "499000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "\u003cul\u003e\u003cli\u003eCốc xay\u0026nbsp;trái cây có thể sạc lại. Được trang bị pin 1500mAh\u003c/li\u003e\u003cli\u003eDi động và thuận tiện mang theo\u003c/li\u003e\u003cli\u003eXay và uống trực tiếp bằng cùng một cốc xay\u003c/li\u003e\u003cli\u003eBật nguồn an toàn (để bật cần nhấn 2 lần)\u003c/li\u003e\u003cli\u003eDễ dàng làm sạch và rửa\u003c/li\u003e\u003cli\u003eVật liệu PCTG chất lượng cao, Không chứa BPA, Chống rơi vỡ, Chống mài mòn\u003c/li\u003e\u003c/ul\u003e",
    },
    {
      productInfo: {
        sku: "220303984",
        skuId: "220303984",
        name: "Máy sấy tóc Philips BHD350/10",
        imageUrl:
          "https://lh3.googleusercontent.com/DGnZiELa3fNhQ6yYHri0k_drScc20JR52tg_B5EIq9yZwsam35TFy9pkoWQPv9kFUaphLg2t5Hoc7VzZ_KTIauP7FpjfVEs5",
        tags: [],
        brand: {
          code: "philips",
          name: "PHILIPS",
          logo: "",
          id: 11729,
        },
        categories: [
          {
            code: "NH12",
            name: "Điện máy",
            id: 386106,
            isAdult: false,
          },
          {
            code: "NH12-03",
            name: "Điện gia dụng",
            id: 386702,
            isAdult: false,
          },
          {
            code: "NH12-03-99",
            name: "Điện gia dụng khác",
            id: 386732,
            isAdult: false,
          },
          {
            code: "NH12-03-99-01",
            name: "Dụng cụ làm đẹp",
            id: 386733,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [
          {
            code: "008",
            name: "Đồ gia dụng",
            id: 1691,
            isAdult: false,
          },
          {
            code: "008-002",
            name: "Thiết bị gia đình",
            id: 1769,
            isAdult: false,
          },
          {
            code: "008-002-011",
            name: "Máy sấy tay",
            id: 1808,
            isAdult: false,
          },
        ],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "may-say-toc-philips-bhd350-10",
        sellerSku: "220303984",
        canonical: "may-say-toc-philips-bhd350-10--s220303984",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "8710103959595",
        shippingType: "NORMAL",
        displayName: "Máy sấy tóc Philips BHD350/10",
        imageLabel: "Máy sấy tóc Philips BHD350/10",
      },
      promotions: [
        {
          id: 500127,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 221000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description: "Oct 2023 | Flash Sales Online - SDA",
          endTimestampSec: "1698166799",
          name: "Oct 2023 | Flash Sales Online - SDA 113",
          type: "product",
          landing: null,
        },
        {
          id: 479586,
          isDefault: true,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: null,
            gifts: [],
            voucher: {
              name: "Mã giảm thêm 10% tối đa 50.000 cho một số bàn ủi hơi nước",
              quantity: 1,
              maxQuantity: 2500,
            },
            bulkDiscount: null,
          },
          applyOn: "product",
          description:
            "Mã giảm thêm 10% tối đa 50.000 cho một số bàn ủi hơi nước",
          endTimestampSec: "1698771599",
          name: "Aug 2023 | Giảm 10% tối đa 50K cho một số Bàn ủi hơi nước khi mua kèm Máy sấy tóc - Gửi SMS",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "890000",
          terminalPrice: "890000",
          latestPrice: "669000",
          discountAmount: "221000",
          discountPercent: 24.83,
          sellPrice: "890000",
          minLatestPrice: "669000",
          maxLatestPrice: "669000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "\u003cp\u003e- Bảo vệ nhiệt (ThermoProtect)\u003cbr\u003e- Chăm sóc ion\u003cbr\u003e- Chế độ cài đặt nhiệt/tốc độ 6\u003cbr\u003e- Chế độ sấy mát\u003cbr\u003e- Móc treo bảo quản\u003cbr\u003e- Động cơ DC\u003cbr\u003e- Điện áp 220-240 V\u003cbr\u003e- Chiều dài dây 1,8 m\u003c/p\u003e",
    },
    {
      productInfo: {
        sku: "220303294",
        skuId: "220303294",
        name: "Máy vắt cam Sharp EJ-J850-BK",
        imageUrl:
          "https://lh3.googleusercontent.com/onGUtk4FUaIZ09K9-tt_iMsFKR2gCYVRKq0OaTd0XDSprCoe--b1zbVMPixPDAlIuCN1hwcckQe3tnSm-LgiunXW6311bf1D",
        tags: ["Sharp-May22"],
        brand: {
          code: "sharp",
          name: "SHARP",
          logo: "",
          id: 0,
        },
        categories: [
          {
            code: "NH12",
            name: "Điện máy",
            id: 386106,
            isAdult: false,
          },
          {
            code: "NH12-03",
            name: "Điện gia dụng",
            id: 386702,
            isAdult: false,
          },
          {
            code: "NH12-03-02",
            name: "Điện gia dụng nấu nướng và chế biến",
            id: 386713,
            isAdult: false,
          },
          {
            code: "NH12-03-02-06",
            name: "Máy xay, ép trái cây",
            id: 386719,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [
          {
            code: "008",
            name: "Đồ gia dụng",
            id: 1691,
            isAdult: false,
          },
          {
            code: "008-001",
            name: "Đồ dùng nhà bếp",
            id: 1692,
            isAdult: false,
          },
          {
            code: "008-001-007",
            name: "Máy xay ép",
            id: 1737,
            isAdult: false,
          },
          {
            code: "008-001-007-007",
            name: "Máy vắt cam",
            id: 1746,
            isAdult: false,
          },
        ],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "may-vat-cam-sharp-ej-j850-bk",
        sellerSku: "220303294",
        canonical: "may-vat-cam-sharp-ej-j850-bk--s220303294",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "4974019136950",
        shippingType: "NORMAL",
        displayName: "Máy vắt cam Sharp EJ-J850-BK",
        imageLabel: "Máy vắt cam Sharp EJ-J850-BK",
      },
      promotions: [
        {
          id: 500136,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 110000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description: "Oct 2023 | Flash Sales Online - SDA",
          endTimestampSec: "1698166799",
          name: "Oct 2023 | Flash Sales Online - SDA 122",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "500000",
          terminalPrice: "500000",
          latestPrice: "390000",
          discountAmount: "110000",
          discountPercent: 22,
          sellPrice: "500000",
          minLatestPrice: "390000",
          maxLatestPrice: "390000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "\u003cp\u003e- Máy vắt cam nhỏ gọn chuyên dùng ép trái cây có múi\u003cbr\u003e- Động cơ êm ái, ép nhanh chóng với công suất 85W 1 tốc độ ép\u003cbr\u003e- Máy ra nước ép trực tiếp tại vòi đặt ly dưới vòi để hứng nước ép\u003cbr\u003e- Bộ vắt và bộ lọc bền chắc chất liệu nhựa ABS an toàn\u003cbr\u003e- Vòi ra nước ép chống nhỏ giọt ngăn rò rỉ nước ép ra ngoài\u003c/p\u003e",
    },
  ],
  filter: {
    attributes: [],
    brands: [],
    priceLte: "0",
    priceGte: "0",
    clearanceTypes: [],
  },
  sellers: [],
  brands: [],
  masterCategories: [],
  suggestedKeyword: "",
  providers: [],
  manufacturers: [],
  seoInfo: {
    siteTitle: "Flash Sales",
    canonical: "",
    metaTitle: "",
    metaKeyword: "",
    shortDescription: "",
    metaDescription: "",
    siteDescription: "",
  },
  breadcrumbs: [],
};
