const data = {
  products: [
    {
      productInfo: {
        sku: "230904005",
        skuId: "230904005",
        name: "Điện thoại Samsung Galaxy A05 (4+128) (Black) (SM-A055FZKGXXV)",
        imageUrl:
          "https://lh3.googleusercontent.com/knEb077WDBllxLpzXhn_3HIAoR-l7TvZzCd2fsUL7P1dOeN5W6WDNQVDBn3xpHIir8jYE37c9s0ZI47I-rtni2dm2SB5xe8shg",
        tags: [],
        brand: {
          code: "samsung",
          name: "SAMSUNG",
          logo: "",
          id: 11735,
        },
        categories: [
          {
            code: "NH10",
            name: "Thiết bị giải trí và kỹ thuật số",
            id: 386104,
            isAdult: false,
          },
          {
            code: "NH10-01",
            name: "Điện thoại và máy tính bảng",
            id: 386542,
            isAdult: false,
          },
          {
            code: "NH10-01-01",
            name: "Điện thoại di động",
            id: 386543,
            isAdult: false,
          },
          {
            code: "NH10-01-01-01",
            name: "Điện thoại phổ thông",
            id: 386544,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "dien-thoai-samsung-galaxy-a05-4-128-black-sm-a055fzkgxxv",
        sellerSku: "230904005",
        canonical:
          "dien-thoai-samsung-galaxy-a05-4-128-black-sm-a055fzkgxxv--s230904005",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "",
        shippingType: "NORMAL",
        displayName:
          "Điện thoại Samsung Galaxy A05 (4+128) (Black) (SM-A055FZKGXXV)",
        imageLabel: "",
      },
      promotions: [
        {
          id: 501485,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 241000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description:
            "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt",
          endTimestampSec: "1698425999",
          name: "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt 63",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "3090000",
          terminalPrice: "3090000",
          latestPrice: "2849000",
          discountAmount: "241000",
          discountPercent: 7.8,
          sellPrice: "3090000",
          minLatestPrice: "2849000",
          maxLatestPrice: "2849000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        '- Chính hãng, Mới 100%, Nguyên seal\u003cbr/\u003e- Màn hình: 6.7" PLS LCD\u003cbr/\u003e- Camera sau: 50MP, 2MP\u003cbr/\u003e- Camera trước: 13MP\u003cbr/\u003e- CPU: MediaTek Helio G85\u003cbr/\u003e- Bộ nhớ: 128GB\u003cbr/\u003e- RAM: 4GB\u003cbr/\u003e- Hệ điều hành: Android',
    },
    {
      productInfo: {
        sku: "230904003",
        skuId: "230904003",
        name: "Điện thoại Samsung Galaxy A05s (4+128) (Black) (SM-A057FZKGXXV)",
        imageUrl:
          "https://lh3.googleusercontent.com/RNYcj0cDnSV1G8Sz9wja1S6XUw4t2P3CeADxTPHPgPSkanI3iYjmb366W57cguyDA3rHJHg8qHtyx17vSZerm8qkZgHclZls",
        tags: [],
        brand: {
          code: "samsung",
          name: "SAMSUNG",
          logo: "",
          id: 11735,
        },
        categories: [
          {
            code: "NH10",
            name: "Thiết bị giải trí và kỹ thuật số",
            id: 386104,
            isAdult: false,
          },
          {
            code: "NH10-01",
            name: "Điện thoại và máy tính bảng",
            id: 386542,
            isAdult: false,
          },
          {
            code: "NH10-01-01",
            name: "Điện thoại di động",
            id: 386543,
            isAdult: false,
          },
          {
            code: "NH10-01-01-01",
            name: "Điện thoại phổ thông",
            id: 386544,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "dien-thoai-samsung-galaxy-a05s-4-128-black-sm-a057fzkgxxv",
        sellerSku: "230904003",
        canonical:
          "dien-thoai-samsung-galaxy-a05s-4-128-black-sm-a057fzkgxxv--s230904003",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "",
        shippingType: "NORMAL",
        displayName:
          "Điện thoại Samsung Galaxy A05s (4+128) (Black) (SM-A057FZKGXXV)",
        imageLabel: "",
      },
      promotions: [
        {
          id: 501487,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 300000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description:
            "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt",
          endTimestampSec: "1698425999",
          name: "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt 64",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "3990000",
          terminalPrice: "3990000",
          latestPrice: "3690000",
          discountAmount: "300000",
          discountPercent: 7.52,
          sellPrice: "3990000",
          minLatestPrice: "3690000",
          maxLatestPrice: "3690000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "- Chính hãng, Mới 100%, Nguyên seal\u003cbr/\u003e- Màn hình: PLS LCD\u003cbr/\u003e- Camera sau: 50MP, 2x 2MP\u003cbr/\u003e- Camera trước: 13MP\u003cbr/\u003e- CPU: Snapdragon 680\u003cbr/\u003e- Bộ nhớ: 128GB\u003cbr/\u003e- RAM: 4GB\u003cbr/\u003e- Hệ điều hành: Android",
    },
    {
      productInfo: {
        sku: "230903477",
        skuId: "230903477",
        name: "Điện thoại Samsung Galaxy M34 5G (8+128) (Blue) (SM-M346BZBGXXV)",
        imageUrl:
          "https://lh3.googleusercontent.com/AxVpAyXq5FEdCXAY6WD4EgVSL3sqsssB5ttB7cfiTg5qR1e31_uZxQ4evyf9I1zbDSpzjt5fle2gHPGVpYYyoe3EuNgRcFqk",
        tags: [],
        brand: {
          code: "samsung",
          name: "SAMSUNG",
          logo: "",
          id: 11735,
        },
        categories: [
          {
            code: "NH10",
            name: "Thiết bị giải trí và kỹ thuật số",
            id: 386104,
            isAdult: false,
          },
          {
            code: "NH10-01",
            name: "Điện thoại và máy tính bảng",
            id: 386542,
            isAdult: false,
          },
          {
            code: "NH10-01-01",
            name: "Điện thoại di động",
            id: 386543,
            isAdult: false,
          },
          {
            code: "NH10-01-01-01",
            name: "Điện thoại phổ thông",
            id: 386544,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "dien-thoai-samsung-galaxy-m34-5g-8-128-blue-sm-m346bzbgxxv",
        sellerSku: "230903477",
        canonical:
          "dien-thoai-samsung-galaxy-m34-5g-8-128-blue-sm-m346bzbgxxv--s230903477",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "",
        shippingType: "NORMAL",
        displayName:
          "Điện thoại Samsung Galaxy M34 5G (8+128) (Blue) (SM-M346BZBGXXV)",
        imageLabel: "",
      },
      promotions: [
        {
          id: 501489,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 700000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description:
            "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt",
          endTimestampSec: "1698425999",
          name: "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt 65",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "7990000",
          terminalPrice: "7990000",
          latestPrice: "7290000",
          discountAmount: "700000",
          discountPercent: 8.76,
          sellPrice: "7990000",
          minLatestPrice: "7290000",
          maxLatestPrice: "7290000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "- Chính hãng, Mới 100%, Nguyên seal\u003cbr/\u003e- Màn hình: Super AMOLED\u003cbr/\u003e- Camera sau: 8MP, 2MP, 50MP\u003cbr/\u003e- Camera trước: 13MP\u003cbr/\u003e- CPU: Exynos 1280\u003cbr/\u003e- Bộ nhớ: 128GB\u003cbr/\u003e- RAM: 8GB\u003cbr/\u003e- Hệ điều hành: Android",
    },
    {
      productInfo: {
        sku: "230903514",
        skuId: "230903514",
        name: "Điện thoại Samsung Galaxy M34 5G (8+128) (Dark Blue) (SM-M346BDBGXXV)",
        imageUrl:
          "https://lh3.googleusercontent.com/87KpbWt0IvMd2bXilGvGa1LCY7YoVAs9Zlwuw-2liDICqocLh2dl0h0Bq_THrQWMBEcq4K42RhBfyIKDvcEq2F_v-ydJRYay",
        tags: [],
        brand: {
          code: "samsung",
          name: "SAMSUNG",
          logo: "",
          id: 11735,
        },
        categories: [
          {
            code: "NH10",
            name: "Thiết bị giải trí và kỹ thuật số",
            id: 386104,
            isAdult: false,
          },
          {
            code: "NH10-01",
            name: "Điện thoại và máy tính bảng",
            id: 386542,
            isAdult: false,
          },
          {
            code: "NH10-01-01",
            name: "Điện thoại di động",
            id: 386543,
            isAdult: false,
          },
          {
            code: "NH10-01-01-01",
            name: "Điện thoại phổ thông",
            id: 386544,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "dien-thoai-samsung-galaxy-m34-5g-8-128-dark-blue-sm-m346bdbgxxv",
        sellerSku: "230903514",
        canonical:
          "dien-thoai-samsung-galaxy-m34-5g-8-128-dark-blue-sm-m346bdbgxxv--s230903514",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "",
        shippingType: "NORMAL",
        displayName:
          "Điện thoại Samsung Galaxy M34 5G (8+128) (Dark Blue) (SM-M346BDBGXXV)",
        imageLabel: "",
      },
      promotions: [
        {
          id: 501491,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 700000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description:
            "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt",
          endTimestampSec: "1698425999",
          name: "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt 66",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "7990000",
          terminalPrice: "7990000",
          latestPrice: "7290000",
          discountAmount: "700000",
          discountPercent: 8.76,
          sellPrice: "7990000",
          minLatestPrice: "7290000",
          maxLatestPrice: "7290000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "- Chính hãng, Mới 100%, Nguyên seal\u003cbr/\u003e- Màn hình: Super AMOLED\u003cbr/\u003e- Camera sau: 8MP, 2MP, 50MP\u003cbr/\u003e- Camera trước: 13MP\u003cbr/\u003e- CPU: Exynos 1280\u003cbr/\u003e- Bộ nhớ: 128GB\u003cbr/\u003e- RAM: 8GB\u003cbr/\u003e- Hệ điều hành: Android",
    },
    {
      productInfo: {
        sku: "210600296",
        skuId: "210600296",
        name: "Máy tính bảng Samsung Galaxy Tab A7 Lite 32GB (Bạc) (SM-T225NZSAXEV)",
        imageUrl:
          "https://lh3.googleusercontent.com/UxD3ctjFx5LZl2NCp8IOUZuB_snJMc5x03yoxAtq8G96MlMSuAIxkAPV99k2-MUm2LlHivrsNMtlROVUmUmkeT-C_BgGbKZELQ",
        tags: [],
        brand: {
          code: "samsung",
          name: "SAMSUNG",
          logo: "",
          id: 0,
        },
        categories: [
          {
            code: "NH10",
            name: "Thiết bị giải trí và kỹ thuật số",
            id: 386104,
            isAdult: false,
          },
          {
            code: "NH10-01",
            name: "Điện thoại và máy tính bảng",
            id: 386542,
            isAdult: false,
          },
          {
            code: "NH10-01-02",
            name: "Máy tính bảng",
            id: 386547,
            isAdult: false,
          },
          {
            code: "NH10-01-02-01",
            name: "Máy tính bảng",
            id: 386548,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [
          {
            code: "014",
            name: "Máy tính và thiết bị văn phòng",
            id: 3947,
            isAdult: false,
          },
          {
            code: "014-001",
            name: "Máy tính và máy tính bảng",
            id: 3948,
            isAdult: false,
          },
          {
            code: "014-001-004",
            name: "Máy tính bảng",
            id: 3968,
            isAdult: false,
          },
          {
            code: "014-001-004-001",
            name: "Máy tính bảng Android",
            id: 3969,
            isAdult: false,
          },
        ],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "samsung-galaxy-tab-a7-lite-32gb",
        sellerSku: "210600296",
        canonical: "samsung-galaxy-tab-a7-lite-32gb--p254783",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "8806092513662",
        shippingType: "NORMAL",
        displayName: "Máy tính bảng Samsung Galaxy Tab A7 Lite 32GB",
        imageLabel: "Samsung Galaxy Tab A7 Lite Xám",
      },
      promotions: [
        {
          id: 501493,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 641000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description:
            "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt",
          endTimestampSec: "1698425999",
          name: "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt 67",
          type: "product",
          landing: null,
        },
        {
          id: 426370,
          isDefault: true,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: null,
            gifts: [
              {
                sku: "221101562",
                name: "Bao da nắp gập Tab A7 Lite, Xám (EF-BT220PJEGWW) (Quà tặng)",
                imageUrl:
                  "https://lh3.googleusercontent.com/ZbZHVZ_Rz59_cbMjfHCM2Ere9yqov5BGBhe-46ASR7a0JW1jbayOoQexISRQSnPqtSUP3j61OdSLy96AKDFziP7ipLuChu9Y",
                quantity: 1,
                maxQuantityPerOrder: null,
                quantityDecimal: 1,
                maxQuantityPerOrderDecimal: null,
              },
            ],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description: ".",
          endTimestampSec: "1704041999",
          name: "[Quà tặng] - Bao da nắp gập Tab A7 Lite, Xám (EF-BT220PJEGWW) v1",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "4490000",
          terminalPrice: "4290000",
          latestPrice: "3649000",
          discountAmount: "841000",
          discountPercent: 18.73,
          sellPrice: "4290000",
          minLatestPrice: "3649000",
          maxLatestPrice: "3649000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        '- Chính hãng, Mới 100%, Nguyên seal\u003cbr/\u003e- Màn hình: 8.7", TFT LCD\u003cbr/\u003e- Camera sau: 8MP\u003cbr/\u003e- Camera trước: 2MP\u003cbr/\u003e- Bộ nhớ: 32GB\u003cbr/\u003e- RAM: 3GB\u003cbr/\u003e- Hệ điều hành: Android',
    },
    {
      productInfo: {
        sku: "221003299",
        skuId: "221003299",
        name: "Máy tính bảng Samsung Galaxy Tab S7 FE LTE 4GB/64GB (Đen) (SM-T735NZKAXXV)",
        imageUrl:
          "https://lh3.googleusercontent.com/WDBs6MVNz4hnSM3L1ukUN98WmnDm7Ag_s_AhLNYVWuvg0lYprSCTmtj8UDNCHu621AvU1eUMwlEylid-_JamBDp1Xdo33W0b",
        tags: [],
        brand: {
          code: "samsung",
          name: "SAMSUNG",
          logo: "",
          id: 0,
        },
        categories: [
          {
            code: "NH10",
            name: "Thiết bị giải trí và kỹ thuật số",
            id: 386104,
            isAdult: false,
          },
          {
            code: "NH10-01",
            name: "Điện thoại và máy tính bảng",
            id: 386542,
            isAdult: false,
          },
          {
            code: "NH10-01-02",
            name: "Máy tính bảng",
            id: 386547,
            isAdult: false,
          },
          {
            code: "NH10-01-02-01",
            name: "Máy tính bảng",
            id: 386548,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "may-tinh-bang-samsung-galaxy-tab-s7-fe-4gb-64gb-den",
        sellerSku: "221003299",
        canonical:
          "may-tinh-bang-samsung-galaxy-tab-s7-fe-4gb-64gb-den--s221003299",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "8806092276642",
        shippingType: "NORMAL",
        displayName:
          "Máy tính bảng Samsung Galaxy Tab S7 FE LTE 4GB/64GB (Đen) (SM-T735NZKAXXV)",
        imageLabel: "",
      },
      promotions: [
        {
          id: 501497,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 3300000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description:
            "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt",
          endTimestampSec: "1698425999",
          name: "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt 70",
          type: "product",
          landing: null,
        },
        {
          id: 499326,
          isDefault: true,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: null,
            gifts: [
              {
                sku: "221101564",
                name: "Bao da Tab S7 FE, Đen (EF-BT730PBEGWW) (Quà tặng)",
                imageUrl:
                  "https://lh3.googleusercontent.com/JRDCTgGW1efgzQ2sx6ZjtyEn2rlSkaO0_C7X1ThxkZuTze0-4uKgcCn7mEZB5W194D9-yIayJtpURTDjAhmGxtKswxECLy3_",
                quantity: 1,
                maxQuantityPerOrder: null,
                quantityDecimal: 1,
                maxQuantityPerOrderDecimal: null,
              },
            ],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description: "Quà tặng mặc định",
          endTimestampSec: "1704041999",
          name: "[Quà tặng] - Bao da Tab S7 FE, Đen (EF-BT730PBEGWW) v1",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "13990000",
          terminalPrice: "13190000",
          latestPrice: "9890000",
          discountAmount: "4100000",
          discountPercent: 29.31,
          sellPrice: "13190000",
          minLatestPrice: "9890000",
          maxLatestPrice: "9890000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        '- Chính hãng, Mới 100%, Nguyên seal\u003cbr/\u003e- Màn hình: 12.4" TFT LCD\u003cbr/\u003e- Camera sau: 8MP\u003cbr/\u003e- Camera trước: 5MP\u003cbr/\u003e- CPU: Snapdragon 750G\u003cbr/\u003e- Bộ nhớ: 64GB\u003cbr/\u003e- RAM: 4GB\u003cbr/\u003e- Hệ điều hành: Android',
    },
    {
      productInfo: {
        sku: "211208736",
        skuId: "211208736",
        name: "Máy tính bảng Samsung Galaxy Tab A8 2022 (Xám) (SM-X205NZAEXEV)",
        imageUrl:
          "https://lh3.googleusercontent.com/mL7rqStFFUt2yZXDt1nIQIpZoHtqWQlaKBUPrNuPcRXj1-yokrJ7kdWFT2dzQQpfDgvR57bpwD3CviPFYNj3geoX_CHMZmFf2w",
        tags: [],
        brand: {
          code: "samsung",
          name: "SAMSUNG",
          logo: "",
          id: 11735,
        },
        categories: [
          {
            code: "NH10",
            name: "Thiết bị giải trí và kỹ thuật số",
            id: 386104,
            isAdult: false,
          },
          {
            code: "NH10-01",
            name: "Điện thoại và máy tính bảng",
            id: 386542,
            isAdult: false,
          },
          {
            code: "NH10-01-02",
            name: "Máy tính bảng",
            id: 386547,
            isAdult: false,
          },
          {
            code: "NH10-01-02-01",
            name: "Máy tính bảng",
            id: 386548,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [
          {
            code: "014",
            name: "Máy tính và thiết bị văn phòng",
            id: 3947,
            isAdult: false,
          },
          {
            code: "014-001",
            name: "Máy tính và máy tính bảng",
            id: 3948,
            isAdult: false,
          },
          {
            code: "014-001-004",
            name: "Máy tính bảng",
            id: 3968,
            isAdult: false,
          },
          {
            code: "014-001-004-001",
            name: "Máy tính bảng Android",
            id: 3969,
            isAdult: false,
          },
        ],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "samsung-galaxy-tab-a8-2022",
        sellerSku: "211208736",
        canonical: "samsung-galaxy-tab-a8-2022--p409264",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "8806092970793",
        shippingType: "NORMAL",
        displayName: "Máy tính bảng Samsung Galaxy Tab A8 2022",
        imageLabel: "",
      },
      promotions: [
        {
          id: 501496,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 800000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description:
            "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt",
          endTimestampSec: "1698425999",
          name: "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt 69",
          type: "product",
          landing: null,
        },
        {
          id: 492536,
          isDefault: true,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: null,
            gifts: [
              {
                sku: "221101563",
                name: "Bao da Tab A8, Xám (EF-BX200PJEGWW) (Quà tặng)",
                imageUrl:
                  "https://lh3.googleusercontent.com/Pp2_vEAJJvJ0RoIjvMKRdFwvysn0ACRDc-SY9eMZ_Z44NsZTwEDeEp7WuEYSPWl6KxBpv-sKO9BctcJ4urJAK1Me6aHTnF2z",
                quantity: 1,
                maxQuantityPerOrder: null,
                quantityDecimal: 1,
                maxQuantityPerOrderDecimal: null,
              },
            ],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description: "Quà tặng mặc định",
          endTimestampSec: "1704041999",
          name: "[Quà tặng] - Bao da Tab A8, Xám (EF-BX200PJEGWW) v1",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "6990000",
          terminalPrice: "6590000",
          latestPrice: "5790000",
          discountAmount: "1200000",
          discountPercent: 17.17,
          sellPrice: "6590000",
          minLatestPrice: "5790000",
          maxLatestPrice: "5790000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        "\u003cul\u003e\u003cli\u003eMàn hình lớn 10.5’’ với tỉ lệ 16:10\u003c/li\u003e\u003cli\u003eHệ thống 4 loa hỗ trợ công nghệ Dolby Atmos\u003c/li\u003e\u003cli\u003ePin 7,040mAh cùng sạc nhanh (15W)\u003c/li\u003e\u003cli\u003eThiết kế kim loại nguyên khối cao cấp\u003c/li\u003e\u003cli\u003eTính năng Chia đôi màn hình\u003c/li\u003e\u003cli\u003eTính năng Thao tác tiếp nối\u003c/li\u003e\u003cli\u003eChuyển đổi thông minh - Auto Switch\u003c/li\u003e\u003cli\u003eTrình Ghi màn hình- Screen Recorder: ghi lại khuôn mặt và giọng nói khi đang ghi chú\u003c/li\u003e\u003c/ul\u003e",
    },
    {
      productInfo: {
        sku: "210600295",
        skuId: "210600295",
        name: "Máy tính bảng Samsung Galaxy Tab A7 Lite 32GB (Xám) (SM-T225NZAAXEV)",
        imageUrl:
          "https://lh3.googleusercontent.com/fmgizJSKVgtfVek0i78yDAtKxp1fgTMWXYG8aR1E--8S6-sgeNQq_qRKa3mcoOcNYGMwS2JJpk0FCM_FXWlY92rXzqORhBi7jA",
        tags: ["Payday-t3"],
        brand: {
          code: "samsung",
          name: "SAMSUNG",
          logo: "",
          id: 0,
        },
        categories: [
          {
            code: "NH10",
            name: "Thiết bị giải trí và kỹ thuật số",
            id: 386104,
            isAdult: false,
          },
          {
            code: "NH10-01",
            name: "Điện thoại và máy tính bảng",
            id: 386542,
            isAdult: false,
          },
          {
            code: "NH10-01-02",
            name: "Máy tính bảng",
            id: 386547,
            isAdult: false,
          },
          {
            code: "NH10-01-02-01",
            name: "Máy tính bảng",
            id: 386548,
            isAdult: false,
          },
        ],
        seller: {
          id: 1,
          name: "Phong Vũ",
          displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        },
        provider: {
          id: 1,
          name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
          logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
          slogan: "",
        },
        masterCategories: [
          {
            code: "014",
            name: "Máy tính và thiết bị văn phòng",
            id: 3947,
            isAdult: false,
          },
          {
            code: "014-001",
            name: "Máy tính và máy tính bảng",
            id: 3948,
            isAdult: false,
          },
          {
            code: "014-001-004",
            name: "Máy tính bảng",
            id: 3968,
            isAdult: false,
          },
          {
            code: "014-001-004-001",
            name: "Máy tính bảng Android",
            id: 3969,
            isAdult: false,
          },
        ],
        tax: {
          taxOut: 10,
          taxOutCode: "10",
        },
        warranty: {
          months: 12,
          description: "",
        },
        slug: "samsung-galaxy-tab-a7-lite-32gb",
        sellerSku: "210600295",
        canonical: "samsung-galaxy-tab-a7-lite-32gb--p254783",
        uomCode: "81",
        uomRatio: 1,
        uomName: "Cái",
        manufacturer: null,
        barcode: "8806092513693",
        shippingType: "NORMAL",
        displayName: "Máy tính bảng Samsung Galaxy Tab A7 Lite 32GB",
        imageLabel: "Samsung Galaxy Tab A7 Lite Xám",
      },
      promotions: [
        {
          id: 501495,
          isDefault: false,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: {
              percent: 0,
              maxAmount: 0,
              flat: 641000,
              maxAmountPerOrder: null,
            },
            gifts: [],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description:
            "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt",
          endTimestampSec: "1698425999",
          name: "Sự kiện Z-TECH UNITE: NEWBIE FEST - Khuyến Mãi Đặc Biệt 68",
          type: "product",
          landing: null,
        },
        {
          id: 426370,
          isDefault: true,
          condition: {
            coupon: "",
            orderValueMin: null,
            orderValueMax: null,
            blockSize: 1,
            minQuantity: 1,
            blockSizeDecimal: 1,
            minQuantityDecimal: 1,
            groupBuyInfo: null,
          },
          benefit: {
            discount: null,
            gifts: [
              {
                sku: "221101562",
                name: "Bao da nắp gập Tab A7 Lite, Xám (EF-BT220PJEGWW) (Quà tặng)",
                imageUrl:
                  "https://lh3.googleusercontent.com/ZbZHVZ_Rz59_cbMjfHCM2Ere9yqov5BGBhe-46ASR7a0JW1jbayOoQexISRQSnPqtSUP3j61OdSLy96AKDFziP7ipLuChu9Y",
                quantity: 1,
                maxQuantityPerOrder: null,
                quantityDecimal: 1,
                maxQuantityPerOrderDecimal: null,
              },
            ],
            voucher: null,
            bulkDiscount: null,
          },
          applyOn: "product",
          description: ".",
          endTimestampSec: "1704041999",
          name: "[Quà tặng] - Bao da nắp gập Tab A7 Lite, Xám (EF-BT220PJEGWW) v1",
          type: "product",
          landing: null,
        },
      ],
      totalAvailable: null,
      prices: [
        {
          supplierRetailPrice: "4490000",
          terminalPrice: "4290000",
          latestPrice: "3649000",
          discountAmount: "841000",
          discountPercent: 18.73,
          sellPrice: "4290000",
          minLatestPrice: "3649000",
          maxLatestPrice: "3649000",
        },
      ],
      flashSales: [],
      status: {
        sellingCode: "",
        sellable: true,
      },
      shortDescription:
        '- Chính hãng, Mới 100%, Nguyên seal\u003cbr/\u003e- Màn hình: 8.7", TFT LCD\u003cbr/\u003e- Camera sau: 8MP\u003cbr/\u003e- Camera trước: 2MP\u003cbr/\u003e- Bộ nhớ: 32GB\u003cbr/\u003e- RAM: 3GB\u003cbr/\u003e- Hệ điều hành: Android',
    },
  ],
  filter: {
    attributes: [],
    brands: [],
    priceLte: "0",
    priceGte: "0",
    clearanceTypes: [],
  },
  sellers: [],
  brands: [],
  masterCategories: [],
  suggestedKeyword: "",
  providers: [],
  manufacturers: [],
  seoInfo: {
    siteTitle: "Flash Sales",
    canonical: "",
    metaTitle: "",
    metaKeyword: "",
    shortDescription: "",
    metaDescription: "",
    siteDescription: "",
  },
  breadcrumbs: [],
};
