export const SKU = {
  product: {
    productInfo: {
      sku: "230703422",
      skuId: "230703422",
      name: "Máy tính xách tay/ Laptop Acer Aspire 3 A314-36M-37FM (i3-N305) (Bạc)",
      imageUrl:
        "https://lh3.googleusercontent.com/BmomL_U0wjMpue8fZ3M13tI-zfyzFEbsjgr4ew9we-L2_lvH5xjPv6BSWbobCWG1WEBQUUJVClZr-eUxU7AufxFq6Vkwm6O5",
      tags: [],
      brand: {
        code: "acer",
        name: "ACER",
        logo: "",
        id: 11750,
      },
      categories: [
        {
          code: "NH01",
          name: "Laptop - Máy tính xách tay",
          id: 386095,
          isAdult: false,
        },
        {
          code: "NH01-01",
          name: "Laptop - Máy tính xách tay",
          id: 386110,
          isAdult: false,
        },
        {
          code: "NH01-01-01",
          name: "Laptop - Máy tính xách tay",
          id: 386111,
          isAdult: false,
        },
        {
          code: "NH01-01-01-02",
          name: "Laptop - Máy tính xách tay non-gaming",
          id: 386113,
          isAdult: false,
        },
      ],
      seller: {
        id: 1,
        name: "Phong Vũ",
        displayName: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
        logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
      },
      provider: {
        id: 1,
        name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
        logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
        slogan: "",
      },
      masterCategories: [],
      tax: {
        taxOut: 10,
        taxOutCode: "10",
      },
      warranty: {
        months: 12,
        description: "",
      },
      slug: "laptop-acer-aspire-3-a314-36m-37fm-i3-n305-bac",
      sellerSku: "230703422",
      canonical: "laptop-acer-aspire-3-a314-36m-37fm-i3-n305-bac--s230703422",
      uomCode: "81",
      uomRatio: 1,
      uomName: "Cái",
      manufacturer: null,
      barcode: "4711121627798",
      shippingType: "NORMAL",
      displayName:
        "Laptop ACER Aspire 3 A314-36M-37FM (NX.KDMSV.004) (i3-N305/RAM 8GB/256GB SSD/ Windows 11)",
      imageLabel: "",
    },
    promotions: [
      {
        id: 501069,
        isDefault: false,
        condition: {
          coupon: "",
          orderValueMin: null,
          orderValueMax: null,
          blockSize: 1,
          minQuantity: 1,
          blockSizeDecimal: 1,
          minQuantityDecimal: 1,
          groupBuyInfo: null,
        },
        benefit: {
          discount: {
            percent: 0,
            maxAmount: 0,
            flat: 1000000,
            maxAmountPerOrder: null,
          },
          gifts: [
            {
              sku: "230402215",
              name: "Balo laptop Targus 15.6 TSB883 Black (Safire) (Quà tặng - logo Phong Vũ)",
              imageUrl:
                "https://lh3.googleusercontent.com/cjGDA69efDXQ14jjysvXgtJZMUFFmk8stukaXfL6CmjmVmwYtBAqz03hJ8MhHNCo6FsDsxUCF7OV_ASCKdJIlTGzj3tvcw",
              quantity: 1,
              maxQuantityPerOrder: null,
              quantityDecimal: 1,
              maxQuantityPerOrderDecimal: null,
            },
          ],
          voucher: null,
          bulkDiscount: null,
        },
        applyOn: "product",
        description: "Oct 2023 | Game Changer",
        endTimestampSec: "1698771599",
        name: "Oct 2023 | Game Changer 21 - OL",
        type: "product",
        landing: null,
      },
      {
        id: 499336,
        isDefault: true,
        condition: {
          coupon: "",
          orderValueMin: null,
          orderValueMax: null,
          blockSize: 1,
          minQuantity: 1,
          blockSizeDecimal: 1,
          minQuantityDecimal: 1,
          groupBuyInfo: null,
        },
        benefit: {
          discount: null,
          gifts: [],
          voucher: {
            name: "Mã giảm thêm 5% tối đa 500.000đ cho một số sản phẩm Điện Gia Dụng",
            quantity: 1,
            maxQuantity: 10000,
          },
          bulkDiscount: null,
        },
        applyOn: "product",
        description:
          "Mã giảm thêm 5% tối đa 500.000đ cho một số sản phẩm Điện Gia Dụng",
        endTimestampSec: "1698080398",
        name: "Oct 2023 | Coupon on top 5% MAX 500K cho Điện Gia Dụng khi mua Laptop Bất Kỳ - Mã SMS",
        type: "product",
        landing: null,
      },
      {
        id: 499316,
        isDefault: true,
        condition: {
          coupon: "",
          orderValueMin: null,
          orderValueMax: null,
          blockSize: 1,
          minQuantity: 1,
          blockSizeDecimal: 1,
          minQuantityDecimal: 1,
          groupBuyInfo: null,
        },
        benefit: {
          discount: null,
          gifts: [],
          voucher: {
            name: "Mã giảm thêm 600.000đ cho màn hình LG Gram View",
            quantity: 1,
            maxQuantity: 10000,
          },
          bulkDiscount: null,
        },
        applyOn: "product",
        description: "Mã giảm thêm 600.000đ cho màn hình LG Gram View",
        endTimestampSec: "1704041998",
        name: "Oct 2023 | Ưu đãi mua màn hình LG khi mua kèm Laptop bất kỳ - Mã SMS",
        type: "product",
        landing: null,
      },
      {
        id: 493618,
        isDefault: true,
        condition: {
          coupon: "",
          orderValueMin: null,
          orderValueMax: null,
          blockSize: 1,
          minQuantity: 1,
          blockSizeDecimal: 1,
          minQuantityDecimal: 1,
          groupBuyInfo: null,
        },
        benefit: {
          discount: null,
          gifts: [],
          voucher: {
            name: "Mã giảm thêm 150.000 cho một số chuột Logitech, MSI, Newmen, Asus, Tai nghe Zidli",
            quantity: 1,
            maxQuantity: 10000,
          },
          bulkDiscount: null,
        },
        applyOn: "product",
        description:
          "Mã giảm thêm 150.000 cho một số chuột Logitech, MSI, Newmen, Asus, Tai nghe Zidli",
        endTimestampSec: "1698771598",
        name: "Oct 2023 | Ưu đãi mua chuột và tai nghe khi mua kèm Laptop bất kỳ - Mã SMS",
        type: "product",
        landing: null,
      },
      {
        id: 486920,
        isDefault: true,
        condition: {
          coupon: "",
          orderValueMin: null,
          orderValueMax: null,
          blockSize: 1,
          minQuantity: 1,
          blockSizeDecimal: 1,
          minQuantityDecimal: 1,
          groupBuyInfo: null,
        },
        benefit: {
          discount: null,
          gifts: [],
          voucher: {
            name: "Mã giảm thêm 5% tối đa 300.000đ cho toàn bộ sản phẩm Điện Máy - Điện Gia Dụng",
            quantity: 1,
            maxQuantity: 10000,
          },
          bulkDiscount: null,
        },
        applyOn: "product",
        description:
          "Mã giảm thêm 5% tối đa 300.000đ cho toàn bộ sản phẩm Điện Máy - Điện Gia Dụng",
        endTimestampSec: "1698771599",
        name: "AUG 2023 | Mã giảm thêm 5% tối đa 300.000đ cho Điện Máy - Điện Gia Dụng - Gửi SMS v1",
        type: "product",
        landing: null,
      },
    ],
    totalAvailable: null,
    prices: [
      {
        supplierRetailPrice: "9990000",
        terminalPrice: "9990000",
        latestPrice: "8990000",
        discountAmount: "1000000",
        discountPercent: 10.01,
        sellPrice: "9990000",
        minLatestPrice: "8990000",
        maxLatestPrice: "8990000",
      },
    ],
    flashSales: [],
    productDetail: {
      description: "",
      shortDescription: "",
      attributeSet: {
        id: 1,
        name: "Laptop",
      },
      productLine: null,
      seoInfo: {
        description:
          '<p>Trong thời gian gần đây, Phong Vũ đã nhận được số lượng lớn câu hỏi liên quan đến việc tìm kiếm một dòng sản phẩm <strong>laptop có giá cả hợp lý</strong>,<strong> nhưng vẫn đảm bảo đầy đủ các yếu tố cơ bản</strong>, đặc biệt là đối với học sinh và sinh viên. Những yếu tố như <strong>thiết kế mỏng nhẹ, thời lượng pin kéo dài và màn hình sắc nét thường được ưu tiên</strong> hàng đầu. Nếu bạn đang gặp phải với trường hợp tương tự, Phong Vũ có một gợi ý hữu ích cho bạn là chiếc laptop <strong>ACER Aspire 3 A314-36M-37FM</strong>. Để có cái nhìn tổng quan, bạn hãy dành ít thời gian để tìm hiểu những ưu điểm nổi bật của sản phẩm. Phong Vũ tin rằng sự lựa chọn này sẽ <strong>đáp ứng mọi nhu cầu và kỳ vọng</strong> của bạn.</p><figure class="image"><img src="https://storage.googleapis.com/teko-gae.appspot.com/media/image/2023/8/23/1cfd5eca-3691-411e-a9b5-b82df8599289/acer-a314-thumbnail.jpg"><figcaption>ACER Aspire 3 A314-36M-37FM | Hình minh họa</figcaption></figure><figure class="image"><img src="https://storage.googleapis.com/teko-gae.appspot.com/media/image/2023/8/21/846fb26a-a4b5-4220-ad34-793b7e6d7b47/image.png" alt=""><figcaption>ACER Aspire 3 A314-36M-37FM | Laptop sinh viên, văn phòng giá rẻ đa nhiệm - Nguồn hình ảnh Youtube</figcaption></figure><h2><strong>Về cấu hình: Mạnh trong phân khúc giá</strong></h2><p><a href="https://phongvu.vn/c/laptop-acer"><strong>Laptop ACER</strong></a> Aspire 3 A314-36M-37FM được trang bị <strong>CPU Intel Core i3-N305</strong> - một CPU thuộc <strong>thế hệ thứ 13</strong> của Intel, có <strong>8 nhân và 8 luồng xử lý</strong>, tốc độ xung nhịp từ <strong>1.2 GHz đến 3.8 GHz</strong>. CPU cho phép máy chạy mượt mà các ứng dụng văn phòng, duyệt web hay xem video. CPU này cũng tiết kiệm điện năng hơn, giúp máy hoạt động lâu hơn với một lần sạc</p><figure class="image"><img src="https://storage.googleapis.com/teko-gae.appspot.com/media/image/2023/8/21/fdf2b1e8-5450-4cf4-9d67-df5356f60d2a/image.png" alt="ACER Aspire 3 A314-36M-37FM được trang bị CPU Intel Core i3-N305"><figcaption>ACER Aspire 3 A314-36M-37FM được trang bị CPU Intel Core i3-N305</figcaption></figure><p><a href="https://phongvu.vn/c/laptop-acer-aspire"><strong>Laptop ACER Aspire</strong></a> 3 A314-36M-37FM có <strong>RAM 8GB Onboard LPDDR5 5200MHz</strong>, RAM này cho phép máy chạy đa nhiệm các ứng dụng một cách nhanh chóng và hiệu quả. Tuy nhiên, RAM này không thể nâng cấp được do đã được hàn cố định trên bo mạch chủ.</p><p>Ngoài ra, <a href="https://phongvu.vn/c/laptop-acer-aspire-3"><strong>ACER Aspire 3</strong></a> A314-36M-37FM có ổ cứng <strong>SSD M.2 NVMe dung lượng 256GB</strong> - một loại ổ cứng thể rắn có tốc độ ghi và đọc dữ liệu cao gấp nhiều lần so với HDD truyền thống. SSD này giúp máy khởi động Windows và các ứng dụng nhanh hơn, cũng như bảo vệ dữ liệu tốt hơn. Nếu bạn cần thêm dung lượng lưu trữ, bạn có thể thêm một ổ cứng HDD hoặc SSD ngoài qua cổng USB.</p><h2><strong>Về màn hình: Màu sắc trung thực, chống lóa hiệu quả</strong></h2><p>Laptop ACER Aspire 3 A314-36M-37FM có màn hình <strong>14 inch IPS</strong> độ phân giải<strong> Full HD (1920 x 1080)</strong> - một màn hình có kích thước vừa phải, cho hình ảnh sắc nét và chi tiết. Màn hình này cũng có góc nhìn rộng và màu sắc trung thực, chống lóa, phù hợp cho việc xem phim, học tập hay làm việc. Màn hình này cũng được phủ lớp chống chói, giúp bảo vệ mắt của bạn khi sử dụng máy trong thời gian dài.</p><figure class="image"><img src="https://storage.googleapis.com/teko-gae.appspot.com/media/image/2023/8/21/d32032f8-af90-478f-bba4-c829318de725/image.png" alt="ACER Aspire 3 A314-36M-37FM có màn hình 14 inch IPS | màu sắc trung thực"><figcaption>ACER Aspire 3 A314-36M-37FM có màn hình 14 inch IPS | màu sắc trung thực - Nguồn hình ảnh Youtube</figcaption></figure><h2><strong>Về thiết kế: Siêu mỏng nhẹ, tính di động cao</strong></h2><p>Laptop ACER Aspire 3 A314-36M-37FM có thiết kế đơn giản nhưng không kém phần sang trọng, với vỏ ngoài màu bạc và logo ACER nổi bật. Máy có kích thước <strong>328.3 x 217.2 x 18 mm</strong> và trọng lượng chỉ <strong>1.4 kg</strong>, rất dễ dàng mang theo bên mình. ACER Aspire 3 A314 cũng có <strong>bản lề chắc chắn</strong>, cho phép bạn mở và đóng máy một cách nhẹ nhàng.</p><figure class="image"><img src="https://storage.googleapis.com/teko-gae.appspot.com/media/image/2023/8/21/f4351fa0-f32d-4738-b861-89d1792e4548/image.png" alt=""><figcaption>&nbsp;ACER Aspire 3 A314-36M-37FM siêu mỏng nhẹ tính di động cao - Nguồn hình ảnh Youtube</figcaption></figure><figure class="image"><img src="https://storage.googleapis.com/teko-gae.appspot.com/media/image/2023/8/21/51147dcc-70ba-4545-a90d-03888ced3558/image.png" alt=""><figcaption>&nbsp;ACER Aspire 3 A314-36M-37FM trọng lượng chỉ 1.4 kg - Nguồn hình ảnh Youtube</figcaption></figure><h2><strong>Về Pin: Thời gian sử dụng lâu dài</strong></h2><p>Laptop ACER Aspire 3 A314-36M-37FM có pin liền <strong>dung lượng 40 Wh</strong> - một pin có khả năng cung cấp năng lượng cho máy trong khoảng<strong> 6 đến 8 giờ</strong>, tùy thuộc vào cách sử dụng của bạn. Pin này cho phép bạn sử dụng máy liên tục trong một ngày học tập hay làm việc, mà không lo phải mang theo sạc. Máy cũng hỗ trợ công nghệ sạc nhanh, giúp bạn tiết kiệm thời gian khi cần sạc lại pin.</p><figure class="image"><img src="https://storage.googleapis.com/teko-gae.appspot.com/media/image/2023/8/21/1da139ae-ead7-476d-8ec4-fc057a42d440/image.png" alt=""><figcaption>&nbsp;ACER Aspire 3 A314-36M-37FM | Pin trâu thời gian sử dụng pin lâu dài - Nguồn hình ảnh Youtube</figcaption></figure><h2><strong>Đa dạng cổng kết nối</strong></h2><p>Laptop ACER Aspire 3 A314-36M-37FM có các cổng kết nối đa dạng, bao gồm: <strong>2 x USB 3.2</strong>,<strong> 1 x USB Type-C</strong>, <strong>1 x HDMI, 1 x jack âm thanh 3.5 mm</strong>. Bạn có thể kết nối máy với các thiết bị ngoại vi như chuột, bàn phím, tai nghe, loa, máy in hay màn hình ngoài một cách dễ dàng. Máy cũng có kết nối không dây Wi-Fi 6 và Bluetooth, cho tốc độ truyền dữ liệu nhanh và ổn định.</p><figure class="image"><img src="https://storage.googleapis.com/teko-gae.appspot.com/media/image/2023/8/21/f0397998-3790-4fee-936a-5f96f7149a69/image.png" alt=""><figcaption>ACER Aspire 3 A314-36M-37FM | Đa dạng cổng kết nối - Nguồn hình ảnh Youtube</figcaption></figure><h2><strong>Hệ điều hành Windows 11 Home</strong></h2><p>Laptop ACER Aspire 3 A314-36M-37FM được cài sẵn hệ điều hành Windows 11 Home - phiên bản mới nhất của Windows, có giao diện đẹp mắt và hiện đại. Windows 11 Home mang đến cho bạn nhiều tính năng mới và tiện ích, như menu Start trung tâm, thanh taskbar gọn gàng, widget thông minh, snap layout linh hoạt, Microsoft Store mới…Bạn có thể sử dụng các phần mềm này để soạn thảo văn bản, tính toán bảng biểu, tạo bài thuyết trình hay&nbsp;ghi chú.</p><h2><strong>Mua ngay ACER Aspire 3 A314-36M-37FM chính hãng, giá tốt tại Phong Vũ</strong></h2><p>Laptop ACER Aspire 3 A314-36M-37FM là một chiếc laptop hoàn hảo cho những bạn học sinh, sinh viên hoặc nhân viên văn phòng có nhu cầu sử dụng máy tính cho các tác vụ nhẹ nhàng. Máy có cấu hình mạnh mẽ, màn hình sắc nét, thiết kế siêu mỏng nhẹ, pin trâu, kết nối đa dạng, hệ điều hành Windows 11 Home với mức giá chỉ khoảng 9 triệu đồng, rất phù hợp với túi tiền của hầu hết các bạn trẻ. Nếu bạn quan tâm đến chiếc laptop này, bạn có thể đặt hàng tại Phong Vũ để nhận được nhiều ưu đãi và chế độ bảo hành tốt nhất. Cảm ơn bạn đã theo dõi bài viết của Phong Vũ, chúc bạn sớm tìm được chiếc laptop ưng ý!</p>',
        shortDescription:
          '- CPU: Intel Core i3-N305<br/>- Màn hình: 14" IPS (1920 x 1080)<br/>- RAM: 8GB Onboard LPDDR5 5200MHz <br/>- Đồ họa: Intel UHD Graphics <br/>- Lưu trữ: 256GB SSD M.2 NVMe / <br/>- Hệ điều hành: Windows 11 Home<br/>- 40 Wh Pin liền<br/>- Khối lượng: 1.4kg<br/>- Chuẩn Non-EVO',
        metaTitle:
          "[Độc quyền] Laptop Acer Aspire 3 A314-36M-37FM (i3 thế hệ 13)",
        metaKeyword: "",
        metaDescription:
          'Mua Laptop ACER Aspire 3 A314-36M-37FM (NX.KDMSV.004) NX.KDMSV.004 (14" Full HD/Intel Core i3-N305/8GB/256GB SSD/Windows 11 Home/1.4kg) chính hãng giá rẻ ✅Nhận ngay ưu đãi ✓Hỗ trợ trả góp 0% ✓Giao hàng toàn quốc',
      },
      attributeGroups: [
        {
          id: 0,
          name: "Thương hiệu",
          value: "ACER",
          priority: 0,
          parentId: 7439,
        },
        {
          id: 0,
          name: "Bảo hành",
          value: "12 tháng",
          priority: 1,
          parentId: 7439,
        },
        {
          id: 7439,
          name: "Thông tin chung",
          value: "",
          priority: 1,
          parentId: 0,
        },
        {
          id: 0,
          name: "Series laptop",
          value: "Aspire 3",
          priority: 3,
          parentId: 7439,
        },
        {
          id: 0,
          name: "Part-number",
          value: "NX.KDMSV.004",
          priority: 5,
          parentId: 7439,
        },
        {
          id: 0,
          name: "Màu sắc",
          value: "Bạc",
          priority: 6,
          parentId: 7439,
        },
        {
          id: 0,
          name: "Nhu cầu",
          value: "Văn phòng, Học sinh - Sinh viên",
          priority: 7,
          parentId: 7439,
        },
        {
          id: 7440,
          name: "Cấu hình chi tiết",
          value: "",
          priority: 9,
          parentId: 0,
        },
        {
          id: 7441,
          name: "Thế hệ CPU",
          value: " Core i3 , Non-EVO ",
          priority: 10,
          parentId: 7440,
        },
        {
          id: 7442,
          name: "CPU",
          value: " Intel Core i3-N305 ( 3.80 GHz / 6MB / 8 nhân, 8 luồng )",
          priority: 14,
          parentId: 7440,
        },
        {
          id: 7443,
          name: "Chip đồ họa",
          value: " Intel UHD Graphics ",
          priority: 20,
          parentId: 7440,
        },
        {
          id: 7444,
          name: "RAM",
          value: " 8GB Onboard  LPDDR5  5200MHz ( 1 Khe cắm ",
          priority: 25,
          parentId: 7440,
        },
        {
          id: 7445,
          name: "Màn hình",
          value:
            ' 14" ( 1920 x 1080 ) Full HD  IPS  không cảm ứng , HD webcam ',
          priority: 32,
          parentId: 7440,
        },
        {
          id: 7446,
          name: "Lưu trữ",
          value: " 256GB SSD M.2 NVMe /",
          priority: 41,
          parentId: 7440,
        },
        {
          id: 7447,
          name: "Số cổng lưu trữ tối đa",
          value: " 1 x M.2 NVMe ",
          priority: 46,
          parentId: 7440,
        },
        {
          id: 7448,
          name: "Kiểu khe M.2 hỗ trợ",
          value: " M.2 NVMe ",
          priority: 49,
          parentId: 7440,
        },
        {
          id: 7449,
          name: "Cổng xuất hình",
          value: " 1 x HDMI ",
          priority: 51,
          parentId: 7440,
        },
        {
          id: 7450,
          name: "Cổng kết nối",
          value: " 1 x USB Type C / DisplayPort , 2 x USB 3.2 , Audio combo ",
          priority: 55,
          parentId: 7440,
        },
        {
          id: 7451,
          name: "Kết nối không dây",
          value: " WiFi 802.11ax (Wifi 6) , Bluetooth ",
          priority: 64,
          parentId: 7440,
        },
        {
          id: 7452,
          name: "Bàn phím",
          value: " thường , không phím số , không đèn ",
          priority: 67,
          parentId: 7440,
        },
        {
          id: 7453,
          name: "Hệ điều hành",
          value: " Windows 11 Home  Windows 11 ",
          priority: 71,
          parentId: 7440,
        },
        {
          id: 7454,
          name: "Kích thước",
          value: " 328.3 x 217.15 x 18 mm ",
          priority: 74,
          parentId: 7440,
        },
        {
          id: 7455,
          name: "Pin",
          value: " 40 Wh , Pin liền ",
          priority: 76,
          parentId: 7440,
        },
        {
          id: 7456,
          name: "Khối lượng",
          value: " 1.4 kg",
          priority: 80,
          parentId: 7440,
        },
        {
          id: 7457,
          name: "Thông tin khác",
          value: "",
          priority: 83,
          parentId: 0,
        },
        {
          id: 7460,
          name: "Đèn LED trên máy",
          value: " không đèn ",
          priority: 88,
          parentId: 7457,
        },
        {
          id: 7461,
          name: "Phụ kiện đi kèm",
          value: " Adapter, dây nguồn ",
          priority: 90,
          parentId: 7457,
        },
        {
          id: 4059,
          name: "Thông tin kích thước",
          value: "",
          priority: 94,
          parentId: 0,
        },
      ],
      images: [
        {
          url: "https://lh3.googleusercontent.com/BmomL_U0wjMpue8fZ3M13tI-zfyzFEbsjgr4ew9we-L2_lvH5xjPv6BSWbobCWG1WEBQUUJVClZr-eUxU7AufxFq6Vkwm6O5",
          priority: 1,
          label: "",
        },
        {
          url: "https://lh3.googleusercontent.com/Cgt-dMuQOYlpXw6JwGUf0-gkErJBGqcPVLsg0VmAxefdlp7bBmxqlxLyqOok2TTGUDz1yWfD--sMUs1VeJrcIbDIif0OcioN",
          priority: 2,
          label: "",
        },
        {
          url: "https://lh3.googleusercontent.com/A2CAnMbhuHMNTFBV-idB5TT-ppCi3i0mALNB_vGCkRlIWQ3Xcy9MmD9CU5_DOTzGfwm1dTS8431efB_Aw7Onr0C4jjMNibxf_w",
          priority: 3,
          label: "",
        },
        {
          url: "https://lh3.googleusercontent.com/OPYA2E7eZ6gVzX3sX1qEkwDzK0tXuJl-WFIlSL9rz_WMpuu_DQQu06NCAOZ9m7vmEIjfxXuZQRfttW1-NJwpETWa_xt3ENsHNQ",
          priority: 4,
          label: "",
        },
        {
          url: "https://lh3.googleusercontent.com/awXbDOrta3HE6ha4CkIsFBY7cYmm9_2DYER7T33nnV9e0LlexfCJl1qM9yosNoi5a8n0x1T6xP4q4aTMXgP8_YEV7fTPxChXhQ",
          priority: 5,
          label: "",
        },
        {
          url: "https://lh3.googleusercontent.com/PsUuI2hwkVW80oomorNr55Q8oZROdeeunKN5qgWM7Z8yxeOTrfS3HH4rwDK3nOdaH0aRchG4AMz1EjHcW9YvqK1Irspu-9bo",
          priority: 6,
          label: "",
        },
        {
          url: "https://lh3.googleusercontent.com/6yGbTy8Nm6cQehNU7plm9GD3shAGR2pJdCG-4CxzJwmD5ZAaAGvyg6YFNjz2Ovn1u-kDmOBcyhBMXReNNPr0_uYkdw9WMzw",
          priority: 7,
          label: "",
        },
      ],
      productGroup: {
        id: 521997,
        name: "Máy tính xách tay/ Laptop Acer Aspire 3 A314-36M-37FM (i3-N305) (Bạc)",
        visible: "individual",
        configurations: [],
        variants: [],
        combineVariantSEO: false,
      },
      barcode: "4711121627798",
      attributes: [
        {
          code: "uom",
          name: "Đơn vị tính",
          values: ["Cái"],
          id: 0,
        },
        {
          code: "uom_ratio",
          name: "Tỉ lệ quy đổi",
          values: ["1"],
          id: 0,
        },
        {
          code: "weight",
          name: "Cân nặng (g)",
          values: ["1400"],
          id: 0,
        },
        {
          code: "length",
          name: "Chiều dài (cm)",
          values: ["32.8"],
          id: 0,
        },
        {
          code: "width",
          name: "Chiều rộng (cm)",
          values: ["21.7"],
          id: 0,
        },
        {
          code: "height",
          name: "Chiều cao (cm)",
          values: ["1.8"],
          id: 0,
        },
        {
          code: "pack_weight",
          name: "Cân nặng đóng gói (g)",
          values: ["2500"],
          id: 0,
        },
        {
          code: "pack_length",
          name: "Chiều dài đóng gói (cm)",
          values: ["45.2"],
          id: 0,
        },
        {
          code: "pack_width",
          name: "Chiều rộng đóng gói (cm)",
          values: ["30.2"],
          id: 0,
        },
        {
          code: "pack_height",
          name: "Chiều cao đóng gói (cm)",
          values: ["5"],
          id: 0,
        },
        {
          code: "pvhangban_phanloai",
          name: "Loại hàng",
          values: ["Hàng thông thường"],
          id: 0,
        },
        {
          code: "laptop_series",
          name: "Series laptop",
          values: ["Aspire 3"],
          id: 0,
        },
        {
          code: "laptop_ten",
          name: "Tên",
          values: ["Aspire 3 A314-36M-37FM (NX.KDMSV.004)"],
          id: 0,
        },
        {
          code: "laptop_partnumber",
          name: "Part-number",
          values: ["NX.KDMSV.004"],
          id: 0,
        },
        {
          code: "mau_sac_laptop",
          name: "Màu sắc",
          values: ["Bạc"],
          id: 0,
        },
        {
          code: "nhucausudung",
          name: "Nhu cầu",
          values: ["Văn phòng", "Học sinh - Sinh viên"],
          id: 0,
        },
        {
          code: "laptop_segmentation",
          name: "Phân loại",
          values: ["Non-Gaming"],
          id: 0,
        },
        {
          code: "laptop_seriescpu",
          name: "Series CPU",
          values: ["Core i3"],
          id: 0,
        },
        {
          code: "laptop_thehecpu",
          name: "Thế hệ CPU",
          values: [],
          id: 0,
        },
        {
          code: "Laptop_thehecpufilter",
          name: "Thế hệ CPU",
          values: ["Non-EVO"],
          id: 0,
        },
        {
          code: "laptop_tencpu",
          name: "Tên CPU",
          values: ["Intel Core i3-N305"],
          id: 0,
        },
        {
          code: "laptop_tocdoxulycpu",
          name: "Tốc độ xử lý",
          values: ["3.80 GHz"],
          id: 0,
        },
        {
          code: "laptop_bonhocachecpu",
          name: "Bộ nhớ cache",
          values: ["6MB"],
          id: 0,
        },
        {
          code: "laptop_sonhanluongxulycpu",
          name: "Số nhân/luồng xử lý",
          values: ["8 nhân, 8 luồng"],
          id: 0,
        },
        {
          code: "laptop_tencpurutgon",
          name: "Tên CPU Laptop (rút gọn)",
          values: ["i3-N305"],
          id: 0,
        },
        {
          code: "laptop_chipdohoaroi",
          name: "Chip Đồ họa rời",
          values: [],
          id: 0,
        },
        {
          code: "laptop_dungluongbonhodohoa",
          name: "Bộ nhớ đồ họa rời",
          values: [],
          id: 0,
        },
        {
          code: "laptop_thehebonhodohoa",
          name: "Thế hệ bộ nhớ đồ họa rời",
          values: [],
          id: 0,
        },
        {
          code: "laptop_chipdohoatichhop",
          name: "Đồ họa tích hợp",
          values: ["Intel UHD Graphics"],
          id: 0,
        },
        {
          code: "laptop_dungluongbonho",
          name: "Dung lượng RAM",
          values: ["8GB Onboard"],
          id: 0,
        },
        {
          code: "laptop_bonhofilter",
          name: "Dung lượng RAM",
          values: ["8GB"],
          id: 0,
        },
        {
          code: "laptop_thehebonho",
          name: "Thế hệ RAM",
          values: ["LPDDR5"],
          id: 0,
        },
        {
          code: "laptop_busram",
          name: "Bus RAM",
          values: ["5200MHz"],
          id: 0,
        },
        {
          code: "laptop_sokhecamram",
          name: "Số khe RAM",
          values: ["1 Khe cắm"],
          id: 0,
        },
        {
          code: "laptop_dungluongbonhotoida",
          name: "Dung lượng RAM tối đa",
          values: [],
          id: 0,
        },
        {
          code: "laptop_kichthuocmanhinh",
          name: "Kích thước màn hình",
          values: ['14"'],
          id: 0,
        },
        {
          code: "laptop_dophangiaimanhinh",
          name: "Độ phân giải màn hình",
          values: ["1920 x 1080"],
          id: 0,
        },
        {
          code: "laptop_chuandophangiaimanhinh",
          name: "Chuẩn phân giải",
          values: ["Full HD"],
          id: 0,
        },
        {
          code: "laptop_congnghetamnenmanhinh",
          name: "Công nghệ tấm nền",
          values: ["IPS"],
          id: 0,
        },
        {
          code: "laptop_tansoquetmanhinh",
          name: "Tần số quét",
          values: [],
          id: 0,
        },
        {
          code: "laptop_manhinhcamung",
          name: "Màn hình cảm ứng",
          values: ["không cảm ứng"],
          id: 0,
        },
        {
          code: "laptop_bematmanhinh",
          name: "Bề mặt màn hình",
          values: [],
          id: 0,
        },
        {
          code: "laptop_webcam",
          name: "Webcam",
          values: ["HD webcam"],
          id: 0,
        },
        {
          code: "laptop_dungluongssd",
          name: "Dung lượng SSD",
          values: ["256GB SSD M.2 NVMe"],
          id: 0,
        },
        {
          code: "laptop_dungluongssdfilter",
          name: "Dung lượng SSD",
          values: ["256GB"],
          id: 0,
        },
        {
          code: "laptop_dungluonghdd",
          name: "Dung lương HDD",
          values: [],
          id: 0,
        },
        {
          code: "laptop_dungluonghddfilter",
          name: "Dung lương HDD",
          values: [],
          id: 0,
        },
        {
          code: "laptop_sokheocungsata",
          name: "Số khe SATA",
          values: [],
          id: 0,
        },
        {
          code: "laptop_sokhecamm2",
          name: "Số khe M.2",
          values: ["1 x M.2 NVMe"],
          id: 0,
        },
        {
          code: "laptop_phanloaim2",
          name: "Kiểu khe M.2 hỗ trợ",
          values: ["M.2 NVMe"],
          id: 0,
        },
        {
          code: "laptop_soconghdmi",
          name: "Cổng HDMI",
          values: ["1 x HDMI"],
          id: 0,
        },
        {
          code: "laptop_socongdisplayport",
          name: "Cổng Displayport",
          values: [],
          id: 0,
        },
        {
          code: "laptop_socongvga",
          name: "Cổng VGA/D-sub",
          values: [],
          id: 0,
        },
        {
          code: "laptop_socongusbc",
          name: "Cổng USB Type-C",
          values: ["1 x USB Type C / DisplayPort"],
          id: 0,
        },
        {
          code: "laptop_socongusb31",
          name: "Cổng USB 3.1",
          values: ["2 x USB 3.2"],
          id: 0,
        },
        {
          code: "laptop_socongusb30",
          name: "Cổng USB 3.0",
          values: [],
          id: 0,
        },
        {
          code: "laptop_socongusb20",
          name: "Cổng USB 2.0",
          values: [],
          id: 0,
        },
        {
          code: "laptop_socongthunderbolt",
          name: "Cổng Thunderbolt",
          values: [],
          id: 0,
        },
        {
          code: "laptop_daudocthenhosd",
          name: "Đầu đọc thẻ",
          values: [],
          id: 0,
        },
        {
          code: "laptop_socongketnoiamthanh",
          name: "Cổng âm thanh",
          values: ["Audio combo"],
          id: 0,
        },
        {
          code: "laptop_ketnoilan",
          name: "Kết nối có dây",
          values: [],
          id: 0,
        },
        {
          code: "laptop_ketnoiwlan",
          name: "Kết nối Wifi",
          values: ["WiFi 802.11ax (Wifi 6)"],
          id: 0,
        },
        {
          code: "laptop_ketnoibluetooth",
          name: "Bluetooth",
          values: ["Bluetooth"],
          id: 0,
        },
        {
          code: "laptop_banphimco",
          name: "Bàn phím",
          values: ["thường"],
          id: 0,
        },
        {
          code: "laptop_banphimso",
          name: "Bàn phím số",
          values: ["không phím số"],
          id: 0,
        },
        {
          code: "laptop_dennenbanphim",
          name: "Đèn bàn phím",
          values: ["không đèn"],
          id: 0,
        },
        {
          code: "laptop_hedieuhanh",
          name: "Hệ điều hành",
          values: ["Windows 11 Home"],
          id: 0,
        },
        {
          code: "laptop_hedieuhanhrutgon",
          name: "Hệ điều hành laptop (rút gọn)",
          values: ["Windows 11"],
          id: 0,
        },
        {
          code: "laptop_kichthuoc",
          name: "Kích thước",
          values: ["328.3 x 217.15 x 18 mm"],
          id: 0,
        },
        {
          code: "laptop_dungluongpin",
          name: "Dung lượng pin",
          values: [],
          id: 0,
        },
        {
          code: "laptop_congsuatpin",
          name: "Công suất pin",
          values: ["40 Wh"],
          id: 0,
        },
        {
          code: "laptop_kieupin",
          name: "Kiểu pin",
          values: ["Pin liền"],
          id: 0,
        },
        {
          code: "laptop_khoiluong",
          name: "Khối lượng",
          values: ["1.4"],
          id: 0,
        },
        {
          code: "laptop_filterkhoiluong",
          name: "Khối lượng",
          values: ["1.4 kg - 2 kg"],
          id: 0,
        },
        {
          code: "laptop_baomat",
          name: "Bảo mật",
          values: [],
          id: 0,
        },
        {
          code: "laptop_odiaquang",
          name: "Ổ quang",
          values: [],
          id: 0,
        },
        {
          code: "laptop_den",
          name: "Đèn laptop",
          values: ["không đèn"],
          id: 0,
        },
        {
          code: "laptop_phukiendikem",
          name: "Phụ kiện đi kèm",
          values: ["Adapter, dây nguồn"],
          id: 0,
        },
        {
          code: "laptop_tinhnangdacbiet",
          name: "Tính năng đặc biệt",
          values: ["KHT"],
          id: 0,
        },
      ],
      clearanceTypeName: "",
      clearanceTypeDescription: "",
      clearanceTypeTag: "",
    },
    provider: {
      id: 1,
      name: "CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ PHONG VŨ",
      logo: "https://lh3.googleusercontent.com/qOnchEYD7No58bjEQs5pf_05IV-0DmoaCmEFXD007VHs5cn16LZ6PC98IlY3OiBL9UXsEwNzwiVHRrvSDMQ",
      slogan: "",
    },
    status: {
      sellingCode: "",
      sellable: true,
    },
    salePoint: null,
    warehouseStocks: [],
    productOptions: {
      rows: [],
    },
    availableQuantity: null,
    siteStocks: [],
  },
};
