export const FooterData = [
  {
    title: "Hỗ trợ Khách hàng",
    child: [
      {
        path: "Thẻ ưu đãi",
        url: "#",
      },
      {
        path: "Hướng dẫn mua online",
        url: "#",
      },
      {
        path: "Ưu đãi dành cho Doanh nghiệp",
        url: "#",
      },
      {
        path: "Chính sách trả góp",
        url: "#",
      },
      {
        path: "Dịch vụ sửa chữa",
        url: "#",
      },
    ],
  },
  {
    title: "Chính sách mua hàng",
    child: [
      {
        path: "Điều kiện giao dịch chung",
        url: "#",
      },
      {
        path: "Chính sách bảo hành",
        url: "#",
      },
      {
        path: "Chính sách đổi trả",
        url: "#",
      },
      {
        path: "Giao hàng và Lắp đặt tại nhà",
        url: "#",
      },
      {
        path: "Dịch vụ lắp đặt và nâng cấp PC/ Laptop tại cửa hàng & TTBH",
        url: "#",
      },
    ],
  },
  {
    title: "Thông tin Phong Vũ",
    child: [
      {
        path: "Giới thiệu Phong Vũ",
        url: "#",
      },
      {
        path: "Hệ thống cửa hàng",
        url: "#",
      },
      {
        path: "Trung tâm bảo hành",
        url: "#",
      },
      {
        path: "Chính sách bảo mật",
        url: "#",
      },
      {
        path: "Tin công nghệ",
        url: "#",
      },
      {
        path: "Hỏi đáp",
        url: "#",
      },
      {
        path: "Tuyển dụng",
        url: "#",
      },
    ],
  },
];

export const Product = [
  {
    icon: "https://lh3.googleusercontent.com/lFZZtBMUqkbl9qKKUe3DSmHqpb62UjWrOkxqcJ6lN3yM83Wg2Irp-ZlvkUwGO6TMcsscLELMZa_lN9jo8tKteWsCzmUii7po=rw",
    title: "Laptop",
    detail: [
      {
        group: "Laptop theo thương hiệu",
        child: [
          "Apple (Macbook)",
          "Acer",
          "ASUS",
          "Dell",
          "HP",
          "Lenovo",
          "LG",
          "MSI",
          "Huawei",
          "Gigabyte",
        ],
      },
      {
        group: "Laptop theo cấu hình",
        child: [
          "RTX 30 Series",
          "RTX 40 Series",
          "Intel Pentium/Celeron",
          "Intel Core i3",
          "Intel Core i5",
          "Intel Core i7",
          "Intel Core i9",
          "Intel Core i7",
          "Intel Core i9",
          "Intel Core i7",
          "Intel Core i9",
          "Intel Core i7",
          "Intel Core i9",
          "Intel Core i9",

          "Intel Core i9",
        ],
      },
      {
        group: "Laptop theo kích thước",
        child: [
          "Dưới 13 inch",
          "13-15 inch",
          "Trên 15 inch",
          "Laptop 13 inch",
          "Laptop 14 inch",
          "Laptop 15.6 inch",
          "Laptop 17 inch",
          "Laptop 16 inch",
        ],
      },
      {
        group: "Laptop theo nhu cầu",
        child: [
          "Laptop Sinh viên",
          "Laptop Gaming",
          "Laptop Văn phòng",
          "Laptop cảm ứng 2 trong 1",
          "Laptop Workstation",
          "Laptop đồ họa",
          "Laptop mỏng nhẹ",
        ],
      },
      {
        group: "Laptop theo giá",
        child: [
          "Dưới 10 triệu",
          "10-15 triệu",
          "15-20 triệuu",
          "20-25 triệu",
          "25-30 triệu",
          "Trên 30 triệu",
        ],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/E7coVNI7mvCGp5GASzte71-stIZAYet_sozvQ0A1D_GJfvW1IFJGzymplqvm4A5upZV6ONPQtjgloVYzpHSG09lmQBrEDLU=rw",
    title: "Sản phẩm Apple",
    detail: [
      {
        group: "Macbook",
        child: ["Macbook Air", "Macbook Pro"],
      },
      {
        group: "iMac",
        child: ["iMac Mini"],
      },
      {
        group: "iPhone & iPad",
        child: ["iPhone", "iPad"],
      },
      {
        group: "Apple Watch & Phụ kiện",
        child: [
          "Apple Watch",
          "Củ sạc & cáp sạc",
          "Tai nghe Airpods",
          "Tai nghe Apple Beats",
          "Bàn phím, chuột & bút",
          "Apple TV",
          "Airtag",
          "Apple Care",
        ],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/gmlJNF13XO4tDpnup-D5e7oaomGDsPy5k0rKAzRf-RqIcCAnu2Yq3pnmkMoypBRB8SKtC697eKy2kgaJqQahPA3bkzV7TVCvXA=rw",
    title: "Điện máy - Điện gia dụng",
    detail: [
      {
        group: "Thiết bị nhà bếp",
        child: [
          "Bếp điện từ, bếp gas",
          "Bình đun siêu tốc",
          "Bình thủy điện",
          "Lò nướng",
          "Lò vi sóng",
          "Máy xay thực phẩm",
          "Máy ép trái cây",
          "Máy vắt cam",
          "Máy đánh trứng",
          "Máy làm bánh mì",
          "Máy pha cà phê",
          "Máy rửa chén",
          "Nồi cơm điện",
          "Nồi áp suất",
          "Nồi chiên không dầu",
          "Nồi hấp điện",
        ],
      },
      {
        group: "Máy giặt",
        child: [
          "Electrolux",
          "Sharp",
          "Samsung",
          "LG",
          "Panasonic",
          "Toshiba",
          "AQUA",
          "Casper",
          "Máy giặt cửa trước",
          "Máy giặt cửa trên",
          "Máy giặt Inverter",
          "Máy sấy quần áo",
        ],
      },
      {
        group: "Điều hòa - Máy lạnh",
        child: [
          "LG",
          "Daikin",
          "Casper",
          "LG",
          "Daikin",
          "Casper",
          "LG",
          "Daikin",
          "Casper",
        ],
      },
      {
        group: "Tủ lạnh",
        child: [
          "LG",
          "Daikin",
          "Casper",
          "LG",
          "Daikin",
          "Casper",
          "LG",
          "Daikin",
          "Casper",
        ],
      },
      {
        group: "Thiết bị gia đình",
        child: [
          "Máy lọc không khí",
          "Quạt điều hòa",
          "Máy hút bụi",
          "Máy sấy quần áo",
          "Máy lọc nước",
          "Cây nước nóng lạnh",
          " Bàn ủi",
          "Máy phun sương",
        ],
      },
      {
        group: "Tv",
        child: [
          "Tivi theo thương hiệu",
          "Tivi theo tính năng",
          "Tivi theo độ phân giải",
          "Tivi theo kích thước",
          "Tivi theo giá",
        ],
      },
      {
        group: "Máy nước nóng",
        child: [
          "Ariston",
          "Electrolux",
          "Ferroli",
          "Panasonic",
          " Máy nước nóng trực tiếp",
          "Máy nước nóng gián tiếp",
        ],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/Y7KEp2iUC1syVaF1SQuQ8ZPCLu8PVhCKqadoVKlI8ON-vKqxyvi0EbgM00Ky8Zb_wIcl9Q8HTLZkQj_MuTzqyJhGuLJz8mFTqw=rw",
    title: "PC-Máy tính bộ",
    detail: [
      {
        group: "PC theo thương hiệu",
        child: [
          "Apple (Macbook)",
          "Acer",
          "ASUS",
          "Dell",
          "HP",
          "Lenovo",
          "LG",
          "MSI",
          "Huawei",
          "Gigabyte",
        ],
      },
      {
        group: "PC theo cấu hình",
        child: [
          "RTX 30 Series",
          "RTX 40 Series",
          "Intel Pentium/Celeron",
          "Intel Core i3",
          "Intel Core i5",
          "Intel Core i7",
          "Intel Core i9",
        ],
      },
      {
        group: "PC theo giá tiền",
        child: [
          "Dưới 10 triệu",
          "10-15 triệu",
          "15-20 triệuu",
          "20-25 triệu",
          "25-30 triệu",
        ],
      },
      {
        group: "PC theo cấu hình chip",
        child: [
          "RTX 30 Series",
          "RTX 40 Series",
          "Intel Pentium/Celeron",
          "Intel Core i3",
          "Intel Core i5",
          "Intel Core i7",
          "Intel Core i9",
        ],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/1rbqboPNTH2Gyx3dS28kewywgX0ovZAZHBcstS4KjeJO8j6Qc6Kn19xJH0XpaiqCAj4a-xf_EeAZjlARKaI9mQNBhlHDp6o=rw",
    title: "PC-Màn hình máy tính",
    detail: [
      {
        group: "Theo thương hiệu",
        child: [
          "Apple (Macbook)",
          "Acer",
          "ASUS",
          "Dell",
          "HP",
          "Lenovo",
          "LG",
          "MSI",
          "Huawei",
          "Gigabyte",
        ],
      },
      {
        group: "Tần số quét",
        child: [
          " 60 Hz",
          "75 Hz",
          "100Hz",
          "144 Hz",
          "165 Hz",
          "240 Hz",
          "170hz",
        ],
      },
      {
        group: "Theo giá",
        child: [
          "Dưới 10 triệu",
          "10-15 triệu",
          "15-20 triệuu",
          "20-25 triệu",
          "25-30 triệu",
        ],
      },
      {
        group: "Theo kích cỡ",
        child: [
          "Dưới 19 inch",
          " 24 inch",
          " 27 inch",
          " 32 inch",
          "32 inch trở lên",
        ],
      },
      {
        group: "Theo nhu cầu",
        child: [
          "Màn hình Gaming",
          "Màn hình thiết kế",
          "Màn hình cong",
          "Màn hình văn phòng",
        ],
      },
      {
        group: "Phụ kiện màn hình",
        child: ["Giá đỡ màn hình"],
      },
      {
        group: "Độ phân giải",
        child: ["HD 720p", "Full HD 1080p", "1440p", "UHD 4K"],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/0V32ezrE3Bn6r_lmv4YIyS7Y4QnfVAcjTQ8XjR-86cP_mAtiIzOPsWeEni-MpEklbR5jIfJvtXgD6K-eWhlO7sLsgbxBwsHduQ=rw",
    title: "PC-Linh kiện máy tính",
    detail: [
      {
        group: "CASE-Thùng máy tính",
        child: [
          "SAMA",
          "XIGMATEK",
          "Golden Field",
          "Deepcool",
          "Phong Vũ",
          " Cooler Master",
          "Aerocool",
          "ASUS",
          "MSI",
          "CORSAIR",
          "ANTEC",
          "Cougar",
          "DELUXE",
          "EROSI",
          "GIGABYTE",
          "MIK",
          "SEGOTEP",
        ],
      },
      {
        group: "Ổ cứng",
        child: [
          "WD",
          "Seagate",
          "Kingston",
          "Crucial",
          "Samsung",
          "Kingmax",
          "Crucial",
          "Transcend",
          "Sandisk",
          "Adata",
          "Ổ cứng HDD",
          "Ổ cứng SSD",
          " Ổ cứng di động",
          "Colorful",
          "GIGABYTE",
          "INTEL",
          "Main",
        ],
      },
      {
        group: "Theo giá",
        child: [
          "Dưới 10 triệu",
          "10-15 triệu",
          "15-20 triệuu",
          "20-25 triệu",
          "25-30 triệu",
        ],
      },
      {
        group: "CPU-Bộ vi xử lý",
        child: [
          "Pentium",
          "Core i3",
          "Core i5",
          "Core i7",
          "Core i9",
          "Xeon",
          "Athlon",
          "Ryzen 3",
          "Ryzen 5",
          "Ryzen 7",
          "Ryzen 9",
          "Threadripper",
        ],
      },
      {
        group: "PSU-Nguồn máy tính",
        child: [
          "Cooler Master",
          " Golden Field",
          "CORSAIR",
          "Gigabyte",
          "AcBel",
          "ASUS",
          "MSI",
          "SEGOTEP",
          "XIGMATEK",
          "ANTEC",
          "DEEPCOOL",
          "MIK SPOWER",
        ],
      },
      {
        group: "Tản nhiệt",
        child: ["Tản nhiệt khí", "Tản nhiệt nước", "Quạt Case", "Quạt CPU"],
      },
      {
        group: "Main-Bo mạch chủ",
        child: ["ASUS", "ASRock", "GIGABYTE", "MSI", "Intel", "AMD"],
      },
      {
        group: "RAM-Bộ nhớ",
        child: [
          "Kingston",
          "Gigabyte",
          "KINGMAX",
          "G.SKILL",
          "CORSAIR",
          "Adata",
          "Apacer",
          "Lexar",
          "TEAM",
        ],
      },
      {
        group: "VGA-Card màn hình",
        child: ["ASUS", "Colorful", "GALAX", "GIGABYTE", "MSI", "NVIDIA", "AM"],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/JuVFuLJ2OmqyEO2mtZ0kJTWvACpFkXE_765ihiBIu8WQoHlS-jYXY8zsXDpZUBk26NqRulJ9U_u3DxLcBTxpPGY7n1uzGdKAuA=rw",
    title: "PC-Phụ kiện máy tính",
    detail: [
      {
        group: "Chuột máy tính",
        child: [
          "ASUS",
          "Logitech",
          "Corsair",
          "Razer",
          "SteelSeries",
          "HyperX",
          "AKKO",
          "Fuhlen",
          "MSI",
          "Dell",
          "Newmen",
          "DareU",
          "Microsoft",
          "E-dra",
          "Rapoo",
        ],
      },
      {
        group: "Bàn phím văn phòng",
        child: [
          "Logitech",
          "Rapoo",
          "Microsoft",
          "Asus",
          "Razer",
          "Corsair",
          "HyperX",
          "Newmen",
          "DareU",
          "AKKO",
          "Fuhlen",
          "Dell",
          "Steelseries",
          "E-dra",
          "MSI",
        ],
      },
      {
        group: " Ghế gaming",
        child: [
          "Asus",
          "Corsair",
          "Drift Gaming",
          "E-Dra",
          "MSI",
          "Warrior",
          "AKRacing",
          "Cougar",
          "Razer",
          "MSI",
          "SIHOO",
          "Khác",
        ],
      },
      {
        group: "Lót chuột",
        child: [
          "Logitech",
          "CORSAIR",
          "Razer",
          "SteelSeries",
          "Asus",
          "AKKO",
          "MSI",
          "Newmen",
          "HyperX",
          "Khác",
        ],
      },
      {
        group: " Webcam",
        child: ["Logitech"],
      },
      {
        group: "Phụ kiện chung",
        child: [
          "Bộ lưu điện UPS",
          "Máy ghi âm",
          "Đầu đọc thẻ",
          "Dây loa",
          " Micro USB",
          "HUB USB",
        ],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/qtC62XnXkTsyJbMok7Z7Uu5GOPvhqslzU5YscZZ0HvorTWRs0Qg5s8gWU6l6CTcmc-pQA2y1myJCZ92t9VDq=rw",
    title: "Game & Stream",
    detail: [
      {
        group: "Màn hình Gaming",
        child: [
          "ASUS",
          "Acer",
          "BenQ",
          "Dell",
          "HP",
          "LG",
          "MSI",
          "Viewsonic",
          "Samsung",
        ],
      },
      {
        group: "Chuột Gaming",
        child: [
          "ASUS",
          "Logitech",
          "CORSAIR",
          "Razer",
          "SteelSeries",
          "Zowie",
          "HyperX",
          "AKKO",
          "Khác",
        ],
      },
      {
        group: " Tay cầm & máy chơi game",
        child: [
          "Máy chơi game",
          "PlayStation",
          "Xbox",
          "Logitech",
          "Razer",
          "Rapoo",
          "MSI",
          "E-dra",
          " Khác",
        ],
      },
      {
        group: " Bàn phím Gaming",
        child: [
          "ASUS",
          "Logitech",
          "CORSAIR",
          "Razer",
          "SteelSeries",
          "AKKO",
          "HyperX",
        ],
      },
      {
        group: " Laptop Gaming",
        child: ["ASUS", "MSI", "Dell", "HP", "Acer", "Lenovo"],
      },
      {
        group: "Ghế Gaming",
        child: ["Corsair", "DXRacer", " E-Dra", "  MSI", "Warrior", "Khác"],
      },
      {
        group: "Thiết bị Livestream Game",
        child: ["Capture Card", "Webcam", "Micro", "Stream Deck", "Key Light"],
      },
      {
        group: "Tai nghe Gaming",
        child: [
          "ASUS",
          "Logitech",
          "CORSAIR",
          "Razer",
          "SteelSeries",
          "HyperX",
          "Khác",
        ],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/dkzFFaKYmPLLkPnC-cyefC1u1Qh0Iy_6Loz7adsbIMs-KAK8FA_PwUOklM3gEppESc1uSeaTa63U4Vejifo=rw",
    title: "Điện thoại & Phụ kiện",
    detail: [
      {
        group: "Điện thoại",
        child: [
          "iPhone",
          "Samsung",
          "Asus",
          "Xiaomi",
          "Nubia",
          "ZTE",
          "Dưới 5 triệu",
          "5 - 10 triệu",
          "10 - 15 triệu",
          "15 - 20 triệu",
          "Trên 20 triệu",
        ],
      },
      {
        group: " Máy tính bảng",
        child: [
          "Apple",
          "Samsung",
          "Xiaomi",
          "Lenovo",
          "Dưới 5 triệu",
          "5 - 10 triệu",
          "Trên 10 triệu",
        ],
      },
      {
        group: "Đồng hồ thông minh",
        child: ["Apple", "Samsung", "Garmin", "Fitbit", "Xiaomi", "Khác"],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/slg-pspnUXN25zVZdp_qRMwaTIj008i3gckyGvSYLepffuJZIHNvVo7unNfzkCJZdJw0Om4vMTDttW9z1LZ8ojgVerpfxxM=rw",
    title: "Phụ kiện chung",
    detail: [
      {
        group: "Phụ kiện laptop",
        child: [
          " Giá đỡ",
          " Đế tản nhiệt",
          "Balo - túi chống sốc",
          "Ốp lưng",
          "Dán màn hình",
          "Miếng lót bàn phím",
          "Khác",
        ],
      },
      {
        group: "Linh kiện laptop",
        child: [
          "Bàn phím laptop",
          "Sạc laptop",
          "Pin laptop",
          "RAM laptop",
          "Bộ cấp nguồn",
          "LCD Laptop",
        ],
      },
      {
        group: "Phụ kiện di động",
        child: [
          "Bao da - Ốp lưng",
          "Pin dự phòng",
          "Cáp sạc",
          "Cục sạc",
          "Giá đỡ",
          "Thẻ cào",
        ],
      },
      {
        group: " Hub - bộ chia, chuyển đổi",
        child: [" Unitek", "Ugreen", "HyperDrive", "Belkin", "Khác"],
      },
      {
        group: "Cáp chuyền - cáp nối",
        child: ["Unitek", "Ugreen", "Mazer", "Belkin", "HyperDrive", "Khác"],
      },
      {
        group: "Đầu đọc thẻ nhớ",
        child: [],
      },
      {
        group: "Đầu chuyển",
        child: [],
      },
      {
        group: "Máy ảnh - Máy quay phim",
        child: [" Máy ảnh", "Máy quay phim", "Camera hành trình", "Phụ kiện"],
      },
      {
        group: " Thiết bị lưu trữ",
        child: ["USB", "Thẻ nhớ", "Ổ cứng gắn ngoài"],
      },
      {
        group: "  Ổ cắm điện",
        child: ["LiOA", "Philips"],
      },
      {
        group: "  Phụ kiện khác",
        child: ["Phụ kiện tiện ích"],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/5H5fwM3O8jhVpnNCQziLVok28E6e1c8hT3579MXy3UD4YxKBv7ybyGeRzYrFrPoqvXe20fGGD2wndnDx9EwO_B6yy4kErU8KUw=rw",
    title: "Thiết bị âm thanh",
    detail: [
      {
        group: "Tai nghe",
        child: [
          "Apple",
          "Sony",
          "Logitech",
          "Asus",
          "Razer",
          "HyperX",
          "Zidli",
          "DareU",
          "Steelseries",
          "Soundmax",
          "Soundpeats",
          "E-dra",
          "CORSAIR",
          "HAVIT",
          "Xiaomi",
        ],
      },
      {
        group: "Loại tai nghe",
        child: [
          "In-Ear",
          " On-Ear",
          "Over-Ear",
          "Tai nghe Bluetooth",
          " Tai nghe Gaming",
          "Tai nghe không dây",
        ],
      },
      {
        group: "Loa nghe nhạc",
        child: [
          "Bose",
          "Harman Kardon",
          "JBL",
          "Logitech",
          "Microlab",
          "Sony",
          "SoundMax",
          "Remax",
          "LG",
        ],
      },
      {
        group: " Các loại loa",
        child: [
          "Loa vi tính",
          "Loa Soundbar",
          "Loa Mini",
          "Loa Bluetooth",
          "Loa kéo",
        ],
      },
      {
        group: "MicroPhone",
        child: [
          "SARAMONIC",
          "SALAR",
          "AKG",
          "HYPERX",
          "SENIC",
          "RAZER",
          "BOYA",
        ],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/xFbV1RjiYbdvbqqqRNYPSvZtCa_BnS2eELCT84IKhC2-L2p1w6U58xAP7gBYJZUtPj7v12oZZUBBMUt10pq1rsG41cehjlMn=rw",
    title: "Thiết bị thông minh",
    detail: [
      {
        group: "Thiết bị thông minh",
        child: [
          "Bộ điều khiển trung tâm",
          "Bộ cảm biến",
          "Công tắc thông minh",
          "Xe điện",
          "Khóa cửa thông minh",
          "Ổ cắm thông minh",
          "Thiết bị điều khiển",
          "Chuông báo động",
          "Đèn thông minh",
          "Camera thông minh",
          "Sản phẩm khác",
        ],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/ZLE04QOE4IZuc-3xNfTvx5ekBXb8CGdTCWjoFy1fv4O35fthpkMQzE1aSFWt2gqRomuugbUO4VLFecQikR9f21kBMsvDHAgC=rw",
    title: "Thiết bị văn phòng",
    detail: [
      {
        group: "Thiết bị mạng",
        child: [
          "ASUS",
          "TP-Link",
          "TOTOLINK",
          "D-Link",
          "Tenda",
          "Linksys",
          "DrayTek",
          "Cisco",
          "Router WiFi 6",
          "Router WiFi",
          "WiFi Mesh",
          "Hub - Switch",
          "USB WiFi",
          "USB 3G/4G",
          "Card mạng",
          "Cáp mạng",
        ],
      },
      {
        group: "Thiết bị an ninh",
        child: [
          "KBVISION",
          "HIKVISION",
          "QUESTEK",
          "EZVIZ",
          "Xiaomi",
          "Camera an ninh",
          "Camera WiFi",
          "Đầu ghi hình",
        ],
      },
      {
        group: "Máy in văn phòng",
        child: [
          "Brother",
          "Canon",
          "Epson",
          "HP",
          "Máy in Laser",
          " Máy in kim",
          " Máy in phun",
          "Máy in đa năng",
        ],
      },
      {
        group: "Mực in - Giấy in",
        child: [
          "Mực in Laser",
          "Mực in phun",
          "Mực in máy Fax",
          "Drum",
          "Ruy băng",
          "Giấy in",
        ],
      },
      {
        group: "Thiết bị khác",
        child: [
          "Máy quét mã vạch",
          "Máy đếm tiền",
          "Máy chấm công",
          "Máy tính tiền",
          "Máy hủy tài liệu",
          "Máy ép nhựa",
        ],
      },
      {
        group: "Phần mềm",
        child: ["Windows", "Microsoft Office", "Diệt Virus"],
      },
      {
        group: "Máy Fax",
        child: ["Panasonic", "Brother"],
      },
      {
        group: "Máy Fax",
        child: ["Panasonic", "Brother"],
      },
      {
        group: "Máy chủ Server",
        child: ["Dell", "HP"],
      },
      {
        group: "Máy Scan",
        child: ["Brother", "Canon", "Epson", "HP"],
      },
      {
        group: "Thiết bị trình chiếu",
        child: ["Máy chiếu", " Màn chiếu", "Bút trình chiếu", "Giá treo máy"],
      },
      {
        group: " Thiết bị điện thoại",
        child: [" Điện thoại bàn", "Tổng đài điện thoại"],
      },
      {
        group: "Hàng cũ trưng bày thanh",
        child: [],
      },
    ],
  },
  {
    icon: "https://lh3.googleusercontent.com/xQNTUsKuQP8S_IoRbjRIN28exoDh8lx7reM4I4XpGP7ZPqSDKN8gxhKemblPrKX_-INp9Wu1Q6MnWe3-hjgW=rw",
    title: "Giải pháp doanh nghiệp",
    detail: [
      {
        group: " Thiết bị doanh nghiệp",
        child: [
          "Laptop",
          "Máy tính để bàn",
          "Máy chủ - Server",
          "Ổ cứng mạng - NAS",
          "Phần mềm",
          "Máy chiếu",
          "Máy Photocopy",
        ],
      },
      {
        group: "Thiết bị mạng",
        child: ["Switch"],
      },
      {
        group: "Thiết bị hội nghị",
        child: [
          "Hội nghị truyền hình",
          "Camera hội nghị",
          "Micro hội nghị",
          "Loa hội nghị",
          "Phần mềm hội nghị",
          "Phụ kiện hội nghị",
        ],
      },
      {
        group: "Màn hình quảng cáo chuyên dụng",
        child: [
          "Màn hình khách sạn",
          "Màn hình quảng cáo",
          "Màn hình tương tác - Eboard",
        ],
      },
      {
        group: "Smart POS",
        child: [
          "POS cầm tay",
          "POS để bàn",
          "Kiosk",
          "Bảng giá điện tử",
          "Giải pháp quản lý bán hàng",
        ],
      },
    ],
  },
];

export const DealPro = [
  {
    title: "Màn Hình Giá Sốc",
    desc: "Deal Bật Nốc",
    bgImage:
      "https://lh3.googleusercontent.com/7v3REFEvhC1Aj4LfQZWL52-r94atCT70g9HkbRpQQu7cDcNIzdFsHzqCQttWV-5W2DcyYeKHYTKzL44uydyAhDFLEzga7YWXkQ=rw-w3840",
    countdown: "",
    products: [],
    saleUrl: "",
  },
  {
    title: "Chọn Quà Đúng Gu Săn",
    desc: "Deal Nửa Giá",
    bgImage:
      "  https://lh3.googleusercontent.com/G4E6IOl-UmzXQSM16n-nSeW5Q3QzDfsepLCLGlt7ADT6_-35AMU8xOX1m50zKXDJ2Uv6EroDB6HvDQL_auKRRGN3ltxpThy9Ng=rw-w3840",
    countdown: "",
    products: [],
    saleUrl: "",
  },
  {
    title: "Phụ Kiện Điện Thoại",
    desc: "Sạc Nhanh Tiện Lợi",
    bgImage:
      "https://lh3.googleusercontent.com/WBLtuOErPb6OV4Ij5HZrTRi8sXtN5gum8rWqggsYwjiLGuUpHMjAKFPl0Ya-UxbTRwE-F1wb6azav5GMS1r2cSLwoQkrcSz1=rw-w3840",
    countdown: "",
    products: [],
    saleUrl: "",
  },
  {
    title: "Nâng Cấp Văn Phòng",
    desc: "Quà Tặng Chính Hãng",
    bgImage:
      "https://lh3.googleusercontent.com/BcELBbC8gnIaaMmqm8FYRWiWUAfI1mfXnYT87GZJfllumAlvFG-F53O6SlgsVOxo7eijs2N1DUGnW9GslSzGtUKqt9kYiws=rw-w3840",
    countdown: "",
    products: [],
    saleUrl: "",
  },
];
